import { STARTER_SOURCE_NOTE } from "./schema.js";
import { aqaBiologyGcseSpecEntries } from "./aqaBiologyGcse.js";
import { aqaCombinedScienceTrilogySpecEntries } from "./aqaCombinedScienceTrilogy.js";

/** @type {import("./schema.js").SpecTopicEntry[]} */
export const specEntries = [
  ...aqaCombinedScienceTrilogySpecEntries,
  ...aqaBiologyGcseSpecEntries,
  {
    id: "aqa-ks4gcse-chemistry-atomic-structure",
    board: "AQA",
    subject: "Chemistry",
    keyStage: "KS4 - GCSE",
    qualification: "GCSE",
    topic: "Atomic structure",
    specCode: "Starter",
    title: "Atomic structure",
    requiredContent: [
      "Atoms contain protons, neutrons, electrons (overview)",
      "Electronic structure introduced in outline",
      "Link proton number to element identity",
      "Mass number as protons + neutrons (conceptual)",
    ],
    requiredSkills: [],
    requiredPracticals: [],
    commonMisconceptions: [],
    examCommandWords: [],
    linkedTopics: [],
    sourceNote: STARTER_SOURCE_NOTE,
  },
  {
    id: "aqa-ks4gcse-physics-energy-stores",
    board: "AQA",
    subject: "Physics",
    keyStage: "KS4 - GCSE",
    qualification: "GCSE",
    topic: "Energy stores and transfers",
    specCode: "Starter",
    title: "Energy stores and transfers",
    requiredContent: [
      "Identify common energy stores at GCSE level",
      "Energy transfers between stores",
      "Conservation of energy (qualitative statement)",
      "Simple examples linking pathway to store changes",
    ],
    requiredSkills: [],
    requiredPracticals: [],
    commonMisconceptions: [],
    examCommandWords: [],
    linkedTopics: [],
    sourceNote: STARTER_SOURCE_NOTE,
  },
  {
    id: "aqa-ks4gcse-maths-linear-eq",
    board: "AQA",
    subject: "Mathematics",
    keyStage: "KS4 - GCSE",
    qualification: "GCSE",
    topic: "Solving linear equations",
    specCode: "Starter",
    title: "Solving linear equations",
    requiredContent: [
      "Inverse operations to isolate the unknown",
      "One-step and multi-step linear cases",
      "Checking a solution by substitution",
      "Forming a simple equation from a word context",
    ],
    requiredSkills: [],
    requiredPracticals: [],
    commonMisconceptions: [],
    examCommandWords: [],
    linkedTopics: [],
    sourceNote: STARTER_SOURCE_NOTE,
  },
  {
    id: "aqa-ks4gcse-history-ww1-causes",
    board: "AQA",
    subject: "History",
    keyStage: "KS4 - GCSE",
    qualification: "GCSE",
    topic: "Causes of the First World War",
    specCode: "Starter",
    title: "Causes of the First World War",
    requiredContent: [
      "Long-term tensions (high-level overview)",
      "Alliance system introduced as a factor",
      "Crisis / trigger events leading to war (overview)",
      "Use of evidence in explaining causation",
    ],
    requiredSkills: [],
    requiredPracticals: [],
    commonMisconceptions: [],
    examCommandWords: [],
    linkedTopics: [],
    sourceNote: STARTER_SOURCE_NOTE,
  },
];
