import { OFFICIAL_AQA_SOURCE_NOTE } from "./schema.js";

/**
 * AQA GCSE Biology (8461) — topic rows aligned to published subject content
 * (aqa.org.uk …/biology-8461/specification/subject-content/…).
 * Wording kept close to specification statements; teachers must confirm against current PDF/HTML.
 *
 * @type {import("./schema.js").SpecTopicEntry[]}
 */
const RAW_AQA_BIOLOGY_GCSE = [
  {
    id: "aqa-8461-biol-4-1-1-cell-structure",
    board: "AQA",
    subject: "Biology",
    keyStage: "KS4 - GCSE",
    qualification: "GCSE Biology",
    topic: "Cell structure",
    specCode: "4.1.1",
    title: "Cell structure (eukaryotes, prokaryotes, animal and plant cells)",
    requiredContent: [
      "Eukaryotes: genetic material enclosed in a nucleus; plant and animal cells have cell membrane, cytoplasm and nucleus.",
      "Prokaryotes (e.g. bacterial cells): smaller; cell wall and membrane; genetic material as a single DNA loop; may have plasmids; not enclosed in a nucleus.",
      "Relate nucleus, cell membranes, mitochondria, chloroplasts (plants), plasmids (bacterial) to their functions.",
      "Typical animal cell structures: nucleus, cytoplasm, cell membrane, mitochondria, ribosomes.",
      "Plant cells often also have chloroplasts, permanent vacuole with cell sap; plant and algal cells have cellulose cell wall strengthening the cell.",
      "Order-of-magnitude scale of cells; use of prefixes centi, milli, micro, nano as per specification.",
    ],
    requiredSkills: [
      "Recognise, draw and interpret cell images; use estimations of relative size of sub-cellular structures (MS 1d, 3a).",
    ],
    requiredPracticals: [
      "Required practical 1: light microscope — observe, draw and label plant and animal cells; include a magnification scale.",
    ],
    commonMisconceptions: [],
    examCommandWords: ["describe", "explain", "compare"],
    linkedTopics: ["Microscopy", "Cell differentiation", "Plant cell organisation"],
    sourceNote: OFFICIAL_AQA_SOURCE_NOTE,
  },
  {
    id: "aqa-8461-biol-4-1-1-cell-differentiation",
    board: "AQA",
    subject: "Biology",
    keyStage: "KS4 - GCSE",
    qualification: "GCSE Biology",
    topic: "Cell differentiation",
    specCode: "4.1.1.4",
    title: "Cell differentiation",
    requiredContent: [
      "Explain the importance of cell differentiation.",
      "As an organism develops, cells differentiate to form different types of cells.",
      "Most animal cell types differentiate early; many plant cells can differentiate throughout life.",
      "In mature animals cell division is mainly for repair/replacement.",
      "Differentiating cells acquire sub-cellular structures suited to their function — specialised cells.",
    ],
    requiredSkills: [],
    requiredPracticals: [],
    commonMisconceptions: [],
    examCommandWords: ["explain", "describe"],
    linkedTopics: ["Cell structure", "Plant cell organisation", "Inheritance"],
    sourceNote: OFFICIAL_AQA_SOURCE_NOTE,
  },
  {
    id: "aqa-8461-biol-4-1-1-microscopy",
    board: "AQA",
    subject: "Biology",
    keyStage: "KS4 - GCSE",
    qualification: "GCSE Biology",
    topic: "Microscopy",
    specCode: "4.1.1.5",
    title: "Microscopy (light and electron)",
    requiredContent: [
      "How microscopy techniques have developed over time.",
      "Electron microscopes have much higher magnification and resolving power than light microscopes — study sub-cellular detail (differences limited to magnification and resolution).",
      "Carry out calculations using magnification = size of image / size of real object; standard form where appropriate.",
      "Use prefixes centi, milli, micro, nano.",
    ],
    requiredSkills: [],
    requiredPracticals: [
      "Required practical 1 links: use of light microscope, biological drawing and magnification scale.",
    ],
    commonMisconceptions: [],
    examCommandWords: ["explain", "calculate"],
    linkedTopics: ["Cell structure"],
    sourceNote: OFFICIAL_AQA_SOURCE_NOTE,
  },
  {
    id: "aqa-8461-biol-4-2-3-plant-tissues",
    board: "AQA",
    subject: "Biology",
    keyStage: "KS4 - GCSE",
    qualification: "GCSE Biology",
    topic: "Plant cell organisation",
    specCode: "4.2.3.1",
    title: "Plant tissues and the leaf as an organ",
    requiredContent: [
      "Explain how structures of plant tissues relate to their functions.",
      "Tissues include: epidermal tissues, palisade mesophyll, spongy mesophyll, xylem and phloem, meristem at growing tips.",
      "Leaf as an organ: knowledge limited to epidermis, palisade and spongy mesophyll, xylem and phloem, guard cells surrounding stomata.",
    ],
    requiredSkills: [],
    requiredPracticals: [
      "AT 7: observation and drawing of a transverse section of leaf.",
    ],
    commonMisconceptions: [],
    examCommandWords: ["explain", "describe"],
    linkedTopics: ["Transport in plants", "Photosynthesis", "Cell differentiation"],
    sourceNote: OFFICIAL_AQA_SOURCE_NOTE,
  },
  {
    id: "aqa-8461-biol-4-2-3-transport-plants",
    board: "AQA",
    subject: "Biology",
    keyStage: "KS4 - GCSE",
    qualification: "GCSE Biology",
    topic: "Transport in plants",
    specCode: "4.2.3.2",
    title: "Plant organ system — transpiration and translocation",
    requiredContent: [
      "Roots, stem and leaves form a plant organ system transporting substances.",
      "Root hair cells: uptake of water (osmosis) and mineral ions (active transport).",
      "Xylem transports water and mineral ions from roots to stems and leaves; hollow tubes strengthened with lignin; transpiration stream.",
      "Phloem transports dissolved sugars from leaves to the rest of the plant (translocation); tubes of elongated cells; pores in end walls; detailed mechanism not required.",
      "Stomata and guard cells control gas exchange and water loss.",
      "Describe transpiration and translocation including stomatal role.",
      "Explain effects of temperature, humidity, air movement and light intensity on rate of transpiration.",
    ],
    requiredSkills: [
      "MS: rates, means, sampling, surface area/volume where specified; graph skills as per specification.",
    ],
    requiredPracticals: [
      "Measure rate of transpiration via water uptake; investigate stomata distribution (AT 3–7 as listed in specification).",
    ],
    commonMisconceptions: [],
    examCommandWords: ["explain", "describe"],
    linkedTopics: ["Plant cell organisation", "Photosynthesis", "Cell structure"],
    sourceNote: OFFICIAL_AQA_SOURCE_NOTE,
  },
  {
    id: "aqa-8461-biol-4-3-1-communicable",
    board: "AQA",
    subject: "Biology",
    keyStage: "KS4 - GCSE",
    qualification: "GCSE Biology",
    topic: "Communicable diseases",
    specCode: "4.3.1.1",
    title: "Communicable (infectious) diseases and pathogens",
    requiredContent: [
      "Pathogens are microorganisms that cause infectious disease; may be viruses, bacteria, protists or fungi; infect plants or animals.",
      "Spread by direct contact, water or air (explain how viral, bacterial, protist and fungal diseases spread in animals and plants).",
      "Explain how spread can be reduced or prevented.",
      "Bacteria and viruses may reproduce rapidly inside the body.",
      "Bacteria may produce toxins damaging tissues; viruses live and reproduce inside cells, causing cell damage.",
    ],
    requiredSkills: ["WS 1.4 where relevant to evaluation of prevention."],
    requiredPracticals: [],
    commonMisconceptions: [],
    examCommandWords: ["explain", "describe"],
    linkedTopics: [
      "Bacterial diseases",
      "Viral diseases",
      "Human defence systems",
      "Vaccination",
    ],
    sourceNote: OFFICIAL_AQA_SOURCE_NOTE,
  },
  {
    id: "aqa-8461-biol-4-3-1-bacterial",
    board: "AQA",
    subject: "Biology",
    keyStage: "KS4 - GCSE",
    qualification: "GCSE Biology",
    topic: "Bacterial diseases",
    specCode: "4.3.1.3",
    title: "Bacterial diseases (e.g. Salmonella, gonorrhoea)",
    requiredContent: [
      "Salmonella food poisoning: bacteria in food / unhygienic preparation; UK poultry vaccination context; fever, cramps, vomiting, diarrhoea from bacteria and secreted toxins.",
      "Gonorrhoea: STD; discharge and pain on urinating; bacterial cause; antibiotic (e.g. penicillin) resistance; spread by sexual contact; control by antibiotics or barrier contraception (e.g. condom).",
    ],
    requiredSkills: [],
    requiredPracticals: [
      "Links to required practical 2 (antiseptics/antibiotics on bacterial growth) and culturing microorganisms (4.1.1.6).",
    ],
    commonMisconceptions: [],
    examCommandWords: ["explain", "describe"],
    linkedTopics: ["Communicable diseases", "Antibiotics and painkillers", "Human defence systems"],
    sourceNote: OFFICIAL_AQA_SOURCE_NOTE,
  },
  {
    id: "aqa-8461-biol-4-3-1-viral",
    board: "AQA",
    subject: "Biology",
    keyStage: "KS4 - GCSE",
    qualification: "GCSE Biology",
    topic: "Viral diseases",
    specCode: "4.3.1.2",
    title: "Viral diseases (e.g. measles, HIV, TMV)",
    requiredContent: [
      "Measles: fever, rash; serious complications; childhood vaccination; spread by droplets from coughs/sneezes.",
      "HIV: initial flu-like illness; immune cells attacked; antiretroviral control; AIDS when immune system severely damaged; spread by sexual contact or blood (e.g. shared needles).",
      "Tobacco mosaic virus (TMV): plant pathogen; mosaic discolouration on leaves; reduced growth / photosynthesis.",
    ],
    requiredSkills: [],
    requiredPracticals: [],
    commonMisconceptions: [],
    examCommandWords: ["explain", "describe"],
    linkedTopics: ["Communicable diseases", "Vaccination", "Photosynthesis"],
    sourceNote: OFFICIAL_AQA_SOURCE_NOTE,
  },
  {
    id: "aqa-8461-biol-4-3-1-fungal",
    board: "AQA",
    subject: "Biology",
    keyStage: "KS4 - GCSE",
    qualification: "GCSE Biology",
    topic: "Fungal diseases",
    specCode: "4.3.1.4",
    title: "Fungal diseases (e.g. rose black spot)",
    requiredContent: [
      "Rose black spot: purple/black spots on leaves; yellowing and early leaf drop; reduced photosynthesis.",
      "Spread in the environment by water or wind.",
      "Treatment: fungicides and/or removing and destroying affected leaves.",
    ],
    requiredSkills: [],
    requiredPracticals: [],
    commonMisconceptions: [],
    examCommandWords: ["describe", "explain"],
    linkedTopics: ["Communicable diseases", "Plant cell organisation"],
    sourceNote: OFFICIAL_AQA_SOURCE_NOTE,
  },
  {
    id: "aqa-8461-biol-4-3-1-protist",
    board: "AQA",
    subject: "Biology",
    keyStage: "KS4 - GCSE",
    qualification: "GCSE Biology",
    topic: "Protist diseases",
    specCode: "4.3.1.5",
    title: "Protist diseases (e.g. malaria)",
    requiredContent: [
      "Malaria pathogens are protists.",
      "Life cycle includes the mosquito vector.",
      "Recurrent fever; can be fatal.",
      "Control: prevent mosquitos breeding; mosquito nets to avoid bites.",
    ],
    requiredSkills: [],
    requiredPracticals: [],
    commonMisconceptions: [],
    examCommandWords: ["explain", "describe"],
    linkedTopics: ["Communicable diseases", "Human defence systems"],
    sourceNote: OFFICIAL_AQA_SOURCE_NOTE,
  },
  {
    id: "aqa-8461-biol-4-3-1-defence",
    board: "AQA",
    subject: "Biology",
    keyStage: "KS4 - GCSE",
    qualification: "GCSE Biology",
    topic: "Human defence systems",
    specCode: "4.3.1.6",
    title: "Human defence systems",
    requiredContent: [
      "Non-specific defences: skin; nose; trachea and bronchi; stomach.",
      "Immune system destroys pathogens that enter the body.",
      "White blood cells: phagocytosis; antibody production; antitoxin production.",
    ],
    requiredSkills: [],
    requiredPracticals: [],
    commonMisconceptions: [],
    examCommandWords: ["describe", "explain"],
    linkedTopics: ["Vaccination", "Communicable diseases", "Monoclonal antibodies"],
    sourceNote: OFFICIAL_AQA_SOURCE_NOTE,
  },
  {
    id: "aqa-8461-biol-4-3-1-vaccination",
    board: "AQA",
    subject: "Biology",
    keyStage: "KS4 - GCSE",
    qualification: "GCSE Biology",
    topic: "Vaccination",
    specCode: "4.3.1.7",
    title: "Vaccination",
    requiredContent: [
      "How vaccination prevents illness in an individual and how immunising many people reduces pathogen spread.",
      "Small quantities of dead or inactive pathogen stimulate white blood cells to produce antibodies.",
      "On reinfection, rapid antibody response prevents infection.",
      "No recall of specific vaccination schedules or named side effects required.",
    ],
    requiredSkills: ["WS 1.4: evaluate global use of vaccination."],
    requiredPracticals: [],
    commonMisconceptions: [],
    examCommandWords: ["explain", "evaluate"],
    linkedTopics: ["Human defence systems", "Communicable diseases"],
    sourceNote: OFFICIAL_AQA_SOURCE_NOTE,
  },
  {
    id: "aqa-8461-biol-4-3-1-antibiotics",
    board: "AQA",
    subject: "Biology",
    keyStage: "KS4 - GCSE",
    qualification: "GCSE Biology",
    topic: "Antibiotics and painkillers",
    specCode: "4.3.1.8",
    title: "Antibiotics and painkillers",
    requiredContent: [
      "Antibiotics (e.g. penicillin) treat bacterial disease by killing bacteria; match specific bacteria to specific antibiotics.",
      "Antibiotics greatly reduced deaths from bacterial disease; resistant strains are a major concern.",
      "Antibiotics do not kill viruses.",
      "Painkillers and other medicines treat symptoms but do not kill pathogens.",
      "Difficulty of developing antiviral drugs without damaging tissues.",
    ],
    requiredSkills: ["WS 1.4 as specified."],
    requiredPracticals: ["Required practical 2: antiseptics/antibiotics on bacterial growth."],
    commonMisconceptions: [],
    examCommandWords: ["explain", "evaluate"],
    linkedTopics: ["Bacterial diseases", "Drug development"],
    sourceNote: OFFICIAL_AQA_SOURCE_NOTE,
  },
  {
    id: "aqa-8461-biol-4-3-1-drugs",
    board: "AQA",
    subject: "Biology",
    keyStage: "KS4 - GCSE",
    qualification: "GCSE Biology",
    topic: "Drug development",
    specCode: "4.3.1.9",
    title: "Discovery and development of drugs",
    requiredContent: [
      "Traditional sources: plants and microorganisms (e.g. digitalis — foxglove; aspirin — willow; penicillin — Fleming / Penicillium mould).",
      "Many new drugs synthesised; starting point may still be a plant-derived chemical.",
      "Preclinical testing: cells, tissues, live animals; clinical trials: healthy volunteers and patients.",
      "Low doses first; if safe, trials find optimum dose; double-blind trials may use placebo.",
      "Toxicity, efficacy and dose testing; peer review of published results (WS 1.6).",
    ],
    requiredSkills: ["WS 1.6: peer review of trial publications."],
    requiredPracticals: [],
    commonMisconceptions: [],
    examCommandWords: ["describe", "explain"],
    linkedTopics: ["Antibiotics and painkillers", "Monoclonal antibodies"],
    sourceNote: OFFICIAL_AQA_SOURCE_NOTE,
  },
  {
    id: "aqa-8461-biol-4-3-2-monoclonal",
    board: "AQA",
    subject: "Biology",
    keyStage: "KS4 - GCSE",
    qualification: "GCSE Biology",
    topic: "Monoclonal antibodies",
    specCode: "4.3.2",
    title: "Monoclonal antibodies (Biology only, HT only)",
    requiredContent: [
      "Produced from a single clone; bind one site on one protein antigen — specific targeting.",
      "Production outline: mouse lymphocytes stimulated → fused with tumour cell → hybridoma divides and makes antibody → clone hybridomas → collect/purify antibody.",
      "Uses (indicative): diagnosis (e.g. pregnancy tests); measure blood chemicals / detect pathogens; research labelling with fluorescent dye; cancer treatment bound to radioactive substance, drug or growth inhibitor.",
      "Side effects can exceed expectations; ethical evaluation (WS 1.3, 1.5).",
    ],
    requiredSkills: [
      "Given information, explain how a test/treatment works; evaluate advantages and disadvantages.",
    ],
    requiredPracticals: [],
    commonMisconceptions: [],
    examCommandWords: ["describe", "evaluate", "explain"],
    linkedTopics: ["Human defence systems", "Drug development"],
    sourceNote: OFFICIAL_AQA_SOURCE_NOTE,
  },
  {
    id: "aqa-8461-biol-4-4-1-photosynthesis",
    board: "AQA",
    subject: "Biology",
    keyStage: "KS4 - GCSE",
    qualification: "GCSE Biology",
    topic: "Photosynthesis",
    specCode: "4.4.1",
    title: "Photosynthesis",
    requiredContent: [
      "Word equation: carbon dioxide + water → glucose + oxygen (with light); symbols CO2, H2O, O2, C6H12O6.",
      "Photosynthesis as endothermic — energy from environment to chloroplasts via light.",
      "Rate affected by temperature, light intensity, carbon dioxide concentration, chlorophyll amount; measure/calculate rates.",
      {
        text: "Graph limiting factors including HT detail per specification (4.4.1.2).",
        tier: "higher",
      },
      "Glucose may be used for respiration, converted to starch for storage, fat/oil storage, cellulose for cell walls, amino acids/proteins (with nitrate ions from soil).",
    ],
    requiredSkills: ["MS & graph skills listed under 4.4.1.2."],
    requiredPracticals: [
      "Required practical 6: effect of light intensity on rate of photosynthesis (e.g. pondweed).",
    ],
    commonMisconceptions: [],
    examCommandWords: ["explain", "describe", "calculate"],
    linkedTopics: ["Plant cell organisation", "Respiration", "Transport in plants"],
    sourceNote: OFFICIAL_AQA_SOURCE_NOTE,
  },
  {
    id: "aqa-8461-biol-4-4-2-respiration",
    board: "AQA",
    subject: "Biology",
    keyStage: "KS4 - GCSE",
    qualification: "GCSE Biology",
    topic: "Respiration",
    specCode: "4.4.2",
    title: "Aerobic and anaerobic respiration",
    requiredContent: [
      "Cellular respiration: exothermic; transfers energy continuously in living cells for life processes.",
      "Aerobic (with oxygen) vs anaerobic (without); compare products and relative energy transferred.",
      "Aerobic equation: glucose + oxygen → carbon dioxide + water (know symbols).",
      "Anaerobic in muscles: glucose → lactic acid; incomplete oxidation — less energy than aerobic.",
      "Anaerobic in plant/yeast: glucose → ethanol + carbon dioxide; fermentation in yeast (bread, alcohol).",
      "Energy uses: building molecules, movement, keeping warm.",
      "Exercise: heart rate, breathing rate/volume increase; oxygen debt, lactic acid, fatigue.",
      {
        text: "HT: liver removes lactic acid; oxygen debt (definitions and detail per specification).",
        tier: "higher",
      },
    ],
    requiredSkills: [],
    requiredPracticals: [],
    commonMisconceptions: [],
    examCommandWords: ["describe", "explain", "compare"],
    linkedTopics: ["Photosynthesis", "Homeostasis"],
    sourceNote: OFFICIAL_AQA_SOURCE_NOTE,
  },
  {
    id: "aqa-8461-biol-4-5-1-homeostasis",
    board: "AQA",
    subject: "Biology",
    keyStage: "KS4 - GCSE",
    qualification: "GCSE Biology",
    topic: "Homeostasis",
    specCode: "4.5.1",
    title: "Homeostasis",
    requiredContent: [
      "Homeostasis: regulation of internal conditions to maintain optimum function despite internal/external change.",
      "Receptors detect stimuli; coordination centres (e.g. brain, spinal cord, pancreas) process information; effectors (muscles/glands) restore optimum levels.",
    ],
    requiredSkills: [],
    requiredPracticals: [],
    commonMisconceptions: [],
    examCommandWords: ["explain", "describe"],
    linkedTopics: ["Nervous system", "Hormonal control"],
    sourceNote: OFFICIAL_AQA_SOURCE_NOTE,
  },
  {
    id: "aqa-8461-biol-4-5-2-nervous",
    board: "AQA",
    subject: "Biology",
    keyStage: "KS4 - GCSE",
    qualification: "GCSE Biology",
    topic: "Nervous system",
    specCode: "4.5.2",
    title: "The human nervous system",
    requiredContent: [
      "Structure adapted to function: receptors → neurones (electrical impulses) → CNS (brain and spinal cord) → effectors (muscles contract, glands secrete).",
      "Biology only — brain regions (4.5.2.2): cerebral cortex, cerebellum, medulla — identification and functions as per specification.",
      "Biology only — eye structure (4.5.2.3) as required by specification.",
      "Biology only — thermoregulation with skin receptors and thermoregulatory centre (4.5.2.4) as per specification.",
    ],
    requiredSkills: [],
    requiredPracticals: [],
    commonMisconceptions: [],
    examCommandWords: ["explain", "describe"],
    linkedTopics: ["Homeostasis", "Hormonal control"],
    sourceNote: OFFICIAL_AQA_SOURCE_NOTE,
  },
  {
    id: "aqa-8461-biol-4-5-3-hormonal",
    board: "AQA",
    subject: "Biology",
    keyStage: "KS4 - GCSE",
    qualification: "GCSE Biology",
    topic: "Hormonal control",
    specCode: "4.5.3",
    title: "Hormonal coordination in humans",
    requiredContent: [
      "Endocrine system: glands secrete hormones into bloodstream → target organs; slower, longer-lasting than nervous control.",
      "Pituitary gland (master gland) as specified.",
      "Identify gland positions listed in specification (pituitary, pancreas, thyroid, adrenal gland, ovary, testes).",
      "Blood glucose monitored/controlled (insulin/glucagon) as in 4.5.3.2.",
      "Roles of hormones in human reproduction including menstrual cycle (4.5.3.4); contraception and other 4.5.3 subsections per tier statements.",
    ],
    requiredSkills: [],
    requiredPracticals: [],
    commonMisconceptions: [],
    examCommandWords: ["describe", "explain"],
    linkedTopics: ["Homeostasis", "Nervous system", "Inheritance"],
    sourceNote: OFFICIAL_AQA_SOURCE_NOTE,
  },
  {
    id: "aqa-8461-biol-4-6-1-inheritance",
    board: "AQA",
    subject: "Biology",
    keyStage: "KS4 - GCSE",
    qualification: "GCSE Biology",
    topic: "Inheritance",
    specCode: "4.6.1",
    title: "Inheritance (DNA, genes, genetic crosses)",
    requiredContent: [
      "DNA polymer, double helix, chromosomes; gene as a section of DNA coding for a protein; genome defined.",
      "Importance of human genome: disease genes, inherited disorders, migration (as per specification list).",
      "Terms: gamete, chromosome, gene, allele, dominant, recessive, homozygous, heterozygous, genotype, phenotype.",
      "Single-gene examples: e.g. mouse fur; human red–green colour blindness; polydactyly dominant; cystic fibrosis recessive.",
      "Punnett squares and family trees; probability and ratios (MS); many traits are polygenic.",
      "Sex determination: 23 pairs; XX female, XY male.",
    ],
    requiredSkills: ["MS 2c, 2e, 1c, 3a as listed in genetics topics."],
    requiredPracticals: [],
    commonMisconceptions: [],
    examCommandWords: ["explain", "complete", "interpret"],
    linkedTopics: ["Variation and evolution", "Cell differentiation"],
    sourceNote: OFFICIAL_AQA_SOURCE_NOTE,
  },
  {
    id: "aqa-8461-biol-4-6-2-variation-evolution",
    board: "AQA",
    subject: "Biology",
    keyStage: "KS4 - GCSE",
    qualification: "GCSE Biology",
    topic: "Variation and evolution",
    specCode: "4.6.2–4.6.3",
    title: "Variation, evolution, selective breeding and genetics history",
    requiredContent: [
      "Variation: genome × environment → phenotype; genetic and environmental causes.",
      "Mutations continuous; most neutral; some alter phenotype; rare beneficial mutations and selection.",
      "Evolution: inherited characteristics change over time through natural selection; may form new species; all species from simpler forms >3 billion years ago.",
      "Natural selection: suited variants more likely to survive and breed; interbreeding/fertility criterion for new species.",
      "Selective breeding (artificial selection): choose parents with desired traits over generations; risks of inbreeding.",
      "Genetic engineering overview: gene from one organism into another (4.6.2.4); cloning summaries (4.6.2.5) as per specification.",
      {
        text: "Biology only: Darwin/Wallace, acceptance of natural selection, Mendel (4.6.3) as per specification statements.",
        flags: { biologyOnly: true },
      },
    ],
    requiredSkills: ["WS 1.2, 1.3, 1.4 as cited in evolution topics."],
    requiredPracticals: [],
    commonMisconceptions: [],
    examCommandWords: ["describe", "explain", "evaluate"],
    linkedTopics: ["Inheritance", "Ecology"],
    sourceNote: OFFICIAL_AQA_SOURCE_NOTE,
  },
  {
    id: "aqa-8461-biol-4-7-ecology",
    board: "AQA",
    subject: "Biology",
    keyStage: "KS4 - GCSE",
    qualification: "GCSE Biology",
    topic: "Ecology",
    specCode: "4.7",
    title: "Ecology (core principles)",
    requiredContent: [
      "Levels of organisation: individual → population → community → ecosystem (biotic × abiotic).",
      "Interdependence, competition, stable communities; sampling with transects/quadrats where specified.",
      "Abiotic and biotic factors affecting communities (lists as in specification).",
      "Food chains from producers; predator–prey cycles; materials recycled; carbon and water cycles; role of microorganisms.",
      "Biodiversity, human impacts (waste, land use, deforestation, global warming), maintaining biodiversity.",
      {
        text: "Biology only: trophic levels, pyramids of biomass, transfer efficiencies; decomposition; food production topics as per specification.",
        flags: { biologyOnly: true },
      },
    ],
    requiredSkills: ["MS & WS skills referenced in 4.7 practical activities."],
    requiredPracticals: [
      "Required practical 9: population size of a common species; sampling.",
      "Required practical 10 (Biology only): temperature and rate of decay (e.g. milk pH).",
    ],
    commonMisconceptions: [],
    examCommandWords: ["describe", "explain", "evaluate", "calculate"],
    linkedTopics: ["Variation and evolution", "Photosynthesis", "Respiration"],
    sourceNote: OFFICIAL_AQA_SOURCE_NOTE,
  },
];

const ENTRY_OVERRIDES_AQA_BIOLOGY = {
  "aqa-8461-biol-4-3-2-monoclonal": {
    tier: "higher",
    qualificationType: "single-science",
    contentFlags: {
      biologyOnly: true,
      higherOnly: true,
      requiredPractical: false,
    },
  },
};

function buildTaggedAqaBiologyGcseEntries(raw) {
  return raw.map((entry) => {
    const override = ENTRY_OVERRIDES_AQA_BIOLOGY[entry.id] || {};
    const merged = { ...entry, ...override };
    const practCount = (merged.requiredPracticals || []).length;
    const baseFlags = {
      requiredPractical: practCount > 0,
      biologyOnly: false,
      higherOnly: false,
      mathsSkill: false,
      workingScientifically: false,
    };
    const mergedFlags = { ...baseFlags, ...(merged.contentFlags || {}) };
    mergedFlags.requiredPractical =
      merged.contentFlags?.requiredPractical !== undefined
        ? merged.contentFlags.requiredPractical
        : practCount > 0;

    return {
      ...merged,
      qualificationType: merged.qualificationType ?? "single-science",
      tier: merged.tier ?? "both",
      route: merged.route ?? "biology",
      contentFlags: mergedFlags,
    };
  });
}

/** Tagged AQA GCSE Biology (8461) rows — qualification/tier metadata for Phase 2b filtering. */
export const aqaBiologyGcseSpecEntries = buildTaggedAqaBiologyGcseEntries(
  RAW_AQA_BIOLOGY_GCSE
);
