import { OFFICIAL_EDUQAS_SOURCE_NOTE } from "./schema.js";

/**
 * @param {Omit<import("./schema.js").SpecTopicEntry, "board" | "subject" | "keyStage" | "qualification" | "qualificationType" | "route" | "sourceNote"> & { route?: import("./schema.js").SpecRoute }} p
 */
function physRow(p) {
  const {
    id,
    topic,
    specCode,
    title,
    requiredContent,
    requiredSkills,
    requiredPracticals,
    commonMisconceptions,
    examCommandWords,
    linkedTopics,
    tier = "both",
    contentFlags = {},
    route = "physics",
  } = p;
  return {
    id,
    board: "WJEC / Eduqas",
    subject: "Physics",
    keyStage: "KS4 - GCSE",
    qualification: "GCSE Physics",
    qualificationType: "single-science",
    tier,
    route,
    topic,
    specCode,
    title,
    requiredContent,
    requiredSkills: requiredSkills ?? [],
    requiredPracticals: requiredPracticals ?? [],
    commonMisconceptions: commonMisconceptions ?? [],
    examCommandWords: examCommandWords ?? [],
    linkedTopics: linkedTopics ?? [],
    contentFlags,
    sourceNote: OFFICIAL_EDUQAS_SOURCE_NOTE,
  };
}

/** @type {import("./schema.js").SpecTopicEntry[]} */
export const eduqasPhysicsGcseSpecEntries = [
  physRow({
    id: "eduqas-phys-energy-stores",
    topic: "Energy stores and transfers",
    specCode: "WJEC / Eduqas GCSE Physics — Energy",
    title: "Energy stores and transfers",
    requiredContent: [
      "Identify energy in mechanical, thermal, chemical, gravitational, elastic, magnetic, electrostatic, nuclear stores.",
      "Energy transfers via mechanical work, heating, radiation, electrical pathways between stores.",
      "Conservation of energy; efficiency as useful output over total input; wasted energy often ends heating surroundings.",
    ],
    requiredSkills: ["Perform simple efficiency and Sankey-style interpretations as examined."],
    examCommandWords: ["describe", "calculate", "explain"],
    linkedTopics: ["Electricity", "Particle model", "Forces"],
  }),
  physRow({
    id: "eduqas-phys-electricity",
    topic: "Electricity",
    specCode: "WJEC / Eduqas GCSE Physics — Electricity",
    title: "Electricity",
    requiredContent: [
      "Current, potential difference, resistance related by Ohm’s law for many components at constant temperature.",
      "Series: same current; parallel: same pd across branches; combine to predict branch currents.",
      "Domestic AC, plugs, fuses/RCDs; calculate power and energy transferred in kWh contexts.",
    ],
    requiredSkills: ["Analyse simple circuit diagrams and use V = IR appropriately."],
    examCommandWords: ["calculate", "explain", "describe"],
    linkedTopics: ["Energy stores and transfers", "Magnetism and electromagnetism"],
  }),
  physRow({
    id: "eduqas-phys-particle-model",
    topic: "Particle model",
    specCode: "WJEC / Eduqas GCSE Physics — Particle model",
    title: "Particle model",
    requiredContent: [
      "Solids, liquids, gases differ in particle spacing, arrangement, and motion; changes of state are physical.",
      "Internal energy includes kinetic and potential stores of particles; heating may change temperature or cause state change.",
      "Specific heat capacity and specific latent heat link energy input to temperature or phase change (use equations as specified).",
      "Gas pressure from particle collisions with container walls (kinetic model qualitatively).",
    ],
    requiredSkills: ["Use Q = mcΔT and E = mL in standard problems when given."],
    examCommandWords: ["explain", "calculate"],
    linkedTopics: ["Energy stores and transfers", "Forces"],
  }),
  physRow({
    id: "eduqas-phys-radioactivity",
    topic: "Radioactivity",
    specCode: "WJEC / Eduqas GCSE Physics — Radioactivity",
    title: "Radioactivity",
    requiredContent: [
      "Nuclear model: protons, neutrons, electrons; isotopes and unstable nuclei.",
      "Alpha, beta, gamma emission compared for penetration and ionisation; half-life from decay graphs (random process).",
      "Uses and hazards of radiation; contamination vs irradiation at simple safety level.",
    ],
    requiredSkills: ["Estimate half-life or activity trends from tabulated or graphical data."],
    examCommandWords: ["describe", "explain", "compare"],
    linkedTopics: ["Energy stores and transfers", "Forces"],
  }),
  physRow({
    id: "eduqas-phys-forces",
    topic: "Forces",
    specCode: "WJEC / Eduqas GCSE Physics — Forces",
    title: "Forces",
    requiredContent: [
      "Vectors vs scalars; resultant force determines acceleration (Newton’s second in suitable form).",
      "Weight = mg; moments, levers, pressure in fluids; Hooke’s law region for springs.",
      "Speed/velocity/acceleration; interpret distance–time and velocity–time graphs including area and gradient meanings.",
    ],
    requiredSkills: ["Draw and annotate free-body diagrams for prescribed contexts."],
    examCommandWords: ["calculate", "explain", "describe"],
    linkedTopics: ["Energy stores and transfers", "Waves", "Particle model"],
  }),
  physRow({
    id: "eduqas-phys-waves",
    topic: "Waves",
    specCode: "WJEC / Eduqas GCSE Physics — Waves",
    title: "Waves",
    requiredContent: [
      "Transverse vs longitudinal; wave equation v = fλ with consistent units.",
      "Reflection, refraction, absorption at boundaries; electromagnetic spectrum uses and hazards in outline.",
      "Sound as longitudinal; measures of loudness and pitch linked to amplitude and frequency (conceptual).",
    ],
    requiredSkills: ["Use wave diagrams and the wave equation in straightforward calculations."],
    examCommandWords: ["describe", "calculate"],
    linkedTopics: ["Magnetism and electromagnetism", "Radioactivity"],
  }),
  physRow({
    id: "eduqas-phys-magnetism",
    topic: "Magnetism and electromagnetism",
    specCode: "WJEC / Eduqas GCSE Physics — Magnetism",
    title: "Magnetism and electromagnetism",
    requiredContent: [
      "Magnetic fields around permenant magnets and current-carrying wires; right-hand grip rule as specified.",
      "Electromagnets in relays, loudspeakers, scrap separators (principles not full engineering).",
      "Motor effect and simple induction contexts: Fleming’s left-hand rule / generator sketch ideas per specification.",
    ],
    requiredSkills: ["Predict force or field direction for simple motor/generator arrangements."],
    examCommandWords: ["explain", "describe"],
    linkedTopics: ["Electricity", "Energy stores and transfers"],
  }),
  physRow({
    id: "eduqas-phys-space",
    topic: "Space physics",
    specCode: "WJEC / Eduqas GCSE Physics — Space physics",
    title: "Space physics",
    contentFlags: { singleScienceOnly: true },
    requiredContent: [
      "Solar system structure; orbits explained qualitatively by gravitational attraction (circular/elliptical overview).",
      "Life cycle of stars: main sequence, red giant/supergiant, white dwarf vs neutron star / black hole at specification depth.",
      "Red-shift as evidence for expanding universe; Hubble-type relationship introduced conceptually—not full cosmology proofs.",
    ],
    requiredSkills: ["Interpret simple data linking distance and recessional speed qualitatively."],
    examCommandWords: ["describe", "explain"],
    linkedTopics: ["Forces", "Waves", "Radioactivity"],
  }),
];
