import { OFFICIAL_OCR_SOURCE_NOTE } from "./schema.js";

/**
 * @param {Omit<import("./schema.js").SpecTopicEntry, "board" | "subject" | "keyStage" | "qualification" | "qualificationType" | "route" | "sourceNote"> & { route?: import("./schema.js").SpecRoute }} p
 */
function bioRow(p) {
  const {
    id,
    topic,
    specCode,
    title,
    requiredContent,
    requiredSkills,
    requiredPracticals,
    commonMisconceptions,
    examCommandWords,
    linkedTopics,
    tier = "both",
    contentFlags = {},
    route = "biology",
  } = p;
  return {
    id,
    board: "OCR",
    subject: "Biology",
    keyStage: "KS4 - GCSE",
    qualification: "GCSE Biology",
    qualificationType: "single-science",
    tier,
    route,
    topic,
    specCode,
    title,
    requiredContent,
    requiredSkills: requiredSkills ?? [],
    requiredPracticals: requiredPracticals ?? [],
    commonMisconceptions: commonMisconceptions ?? [],
    examCommandWords: examCommandWords ?? [],
    linkedTopics: linkedTopics ?? [],
    contentFlags,
    sourceNote: OFFICIAL_OCR_SOURCE_NOTE,
  };
}

/** @type {import("./schema.js").SpecTopicEntry[]} */
export const ocrBiologyGcseSpecEntries = [
  bioRow({
    id: "ocr-bio-cell-structure",
    topic: "Cell structure",
    specCode: "OCR GCSE Biology — Cell structure",
    title: "Cell structure",
    tier: "both",
    requiredContent: [
      "Eukaryotic cells: distinct nucleus with DNA; typical animal structures include cytoplasm, membrane, mitochondria, ribosomes.",
      "Plant cells add chloroplasts, permanent vacuole, cellulose cell wall; compare scale with prokaryotic cells.",
      "Prokaryotes: genetic material not in a nucleus; cell wall; plasmids optional; smaller than typical eukaryotes.",
      "Relate nucleus, membranes, mitochondria, chloroplasts (where present) to their functional roles.",
    ],
    requiredSkills: [
      "Draw and label cells; estimate relative sizes using standard units and magnification ideas.",
    ],
    examCommandWords: ["describe", "compare", "explain"],
    linkedTopics: ["Microscopy", "Cell differentiation", "Transport in plants"],
  }),
  bioRow({
    id: "ocr-bio-cell-differentiation",
    topic: "Cell differentiation",
    specCode: "OCR GCSE Biology — Cell differentiation",
    title: "Cell differentiation",
    tier: "both",
    requiredContent: [
      "Differentiation forms specialised cells with structures suited to their function as organisms develop.",
      "Stem cells retain potential to divide and differentiate; embryonic vs adult stem cells at overview level.",
      "Plant meristems allow ongoing growth; animal tissues largely differentiate early in development.",
    ],
    requiredSkills: ["Explain examples of specialisation in named tissues or organs."],
    examCommandWords: ["explain", "describe"],
    linkedTopics: ["Cell structure", "Inheritance"],
  }),
  bioRow({
    id: "ocr-bio-microscopy",
    topic: "Microscopy",
    specCode: "OCR GCSE Biology — Microscopy",
    title: "Microscopy",
    tier: "both",
    requiredContent: [
      "Light microscopes use lenses; electron microscopes offer higher resolution for sub-cellular detail (qualitative comparison).",
      "Magnification links image size to real object size; use appropriate prefixes.",
      "Biological drawing conventions: clear labels, no shading detail beyond stippling where required.",
    ],
    requiredSkills: ["Calculate magnification from image and real dimensions where asked."],
    examCommandWords: ["calculate", "compare", "describe"],
    linkedTopics: ["Cell structure"],
  }),
  bioRow({
    id: "ocr-bio-enzymes",
    topic: "Enzymes",
    specCode: "OCR GCSE Biology — Enzymes",
    title: "Enzymes",
    tier: "both",
    requiredContent: [
      "Enzymes are biological catalysts; active site shape complements specific substrates (lock-and-key overview).",
      "Temperature and pH alter rate; extremes can denature the enzyme permanently.",
      "Enzyme concentration and substrate concentration also affect initial rate (interpret simple graphs).",
    ],
    requiredSkills: [
      "Explain rate changes using collision and active-site ideas at GCSE depth.",
    ],
    examCommandWords: ["explain", "describe", "suggest"],
    linkedTopics: ["Respiration", "Photosynthesis"],
  }),
  bioRow({
    id: "ocr-bio-transport-plants",
    topic: "Transport in plants",
    specCode: "OCR GCSE Biology — Transport in plants",
    title: "Transport in plants",
    tier: "both",
    requiredContent: [
      "Water and minerals move from roots via xylem; transpiration stream linked to evaporation from leaves.",
      "Phloem translocates sugars from sources to sinks; bidirectional transport overview.",
      "Guard cells regulate stomatal opening, balancing gas exchange and water loss.",
    ],
    requiredSkills: ["Interpret simple data on transpiration rate under changed conditions."],
    examCommandWords: ["explain", "describe"],
    linkedTopics: ["Photosynthesis", "Ecology"],
  }),
  bioRow({
    id: "ocr-bio-communicable",
    topic: "Communicable diseases",
    specCode: "OCR GCSE Biology — Communicable diseases",
    title: "Communicable diseases",
    tier: "both",
    requiredContent: [
      "Pathogens include bacteria, viruses, protists, fungi; transmission routes vary (contact, air, water, vectors).",
      "Public-health measures reduce spread: vaccination, hygiene, screening, vector control.",
      "Describe outbreak patterns qualitatively from simple data.",
    ],
    requiredSkills: ["Compare strategies to limit spread for two different pathogen types."],
    examCommandWords: ["describe", "explain", "evaluate"],
    linkedTopics: ["Bacterial diseases", "Viral diseases", "Human defence systems"],
  }),
  bioRow({
    id: "ocr-bio-bacterial-diseases",
    topic: "Bacterial diseases",
    specCode: "OCR GCSE Biology — Bacterial diseases",
    title: "Bacterial diseases",
    tier: "both",
    requiredContent: [
      "Bacterial pathogens as cellular organisms; example diseases and transmission as per specification breadth.",
      "Antibiotics target bacterial processes; misuse contributes to antibiotic resistance via selection (overview).",
      "Prevention combines hygiene, vaccination where relevant, and appropriate prescribing.",
    ],
    requiredSkills: ["Explain why antibiotics are ineffective against viral illness."],
    examCommandWords: ["explain", "describe"],
    linkedTopics: ["Communicable diseases", "Human defence systems"],
  }),
  bioRow({
    id: "ocr-bio-viral-diseases",
    topic: "Viral diseases",
    specCode: "OCR GCSE Biology — Viral diseases",
    title: "Viral diseases",
    tier: "both",
    requiredContent: [
      "Viruses require host cells to replicate; structure as nucleic acid plus protein coat at simple level.",
      "Example infections and transmission per OCR Gateway / 21st Century breadth (e.g. airborne vs blood-borne overview).",
      "Vaccination stimulates immune memory without causing full disease.",
    ],
    requiredSkills: ["Contrast viral and bacterial infection in terms of treatment options."],
    examCommandWords: ["describe", "explain"],
    linkedTopics: ["Communicable diseases", "Human defence systems"],
  }),
  bioRow({
    id: "ocr-bio-human-defence",
    topic: "Human defence systems",
    specCode: "OCR GCSE Biology — Human defence systems",
    title: "Human defence systems",
    tier: "both",
    requiredContent: [
      "Non-specific barriers: skin, mucus, acid, clotting—reduce pathogen entry.",
      "Specific response: lymphocytes produce antibodies; phagocytes ingest pathogens.",
      "Vaccination introduces antigens to prime memory cells for faster secondary response.",
    ],
    requiredSkills: ["Outline stimulus–receptor–effector language for fever or blood-glucose control links if assessed."],
    examCommandWords: ["describe", "explain"],
    linkedTopics: ["Viral diseases", "Bacterial diseases", "Homeostasis"],
  }),
  bioRow({
    id: "ocr-bio-photosynthesis",
    topic: "Photosynthesis",
    specCode: "OCR GCSE Biology — Photosynthesis",
    title: "Photosynthesis",
    tier: "both",
    requiredContent: [
      "Photosynthesis converts light energy to chemical energy stored in glucose; occurs in chloroplasts.",
      "Word summary: carbon dioxide + water → glucose + oxygen (light-driven).",
      "Limiting factors: light intensity, carbon dioxide concentration, temperature—interpret simple rate graphs.",
    ],
    requiredSkills: ["Use practical-style data (e.g. bubble count) qualitatively."],
    examCommandWords: ["explain", "describe"],
    linkedTopics: ["Respiration", "Transport in plants", "Ecology"],
  }),
  bioRow({
    id: "ocr-bio-respiration",
    topic: "Respiration",
    specCode: "OCR GCSE Biology — Respiration",
    title: "Respiration",
    tier: "both",
    requiredContent: [
      "Aerobic respiration transfers energy from glucose using oxygen; mitochonria central at GCSE depth.",
      "Anaerobic pathways in human muscle (lactic acid) and yeast (ethanol + CO₂) when oxygen is limited.",
      "Compare relative energy yield in qualitative terms suitable for OCR.",
    ],
    requiredSkills: ["Interpret data comparing respiration rate under exercise or temperature change."],
    examCommandWords: ["compare", "explain"],
    linkedTopics: ["Photosynthesis", "Enzymes", "Ecology"],
  }),
  bioRow({
    id: "ocr-bio-homeostasis",
    topic: "Homeostasis",
    specCode: "OCR GCSE Biology — Homeostasis",
    title: "Homeostasis",
    tier: "both",
    requiredContent: [
      "Homeostasis maintains a stable internal environment despite external change.",
      "Negative feedback reduces deviation from a set point once detected by receptors.",
      "Water balance, core temperature, and blood glucose as exemplar controlled variables (overview).",
    ],
    requiredSkills: ["Sketch or describe a simple negative-feedback loop for one named variable."],
    examCommandWords: ["explain", "describe"],
    linkedTopics: ["Hormonal control", "Nervous system"],
  }),
  bioRow({
    id: "ocr-bio-nervous-system",
    topic: "Nervous system",
    specCode: "OCR GCSE Biology — Nervous system",
    title: "Nervous system",
    tier: "both",
    requiredContent: [
      "Stimulus–receptor–coordinator–effector pathway; reflex arcs for rapid response.",
      "Synapses pass information between neurones chemically; overall transmission is fast and short-lived vs hormones.",
      "Voluntary control via motor neurones; sensory neurones carry information to the CNS (conceptual).",
    ],
    requiredSkills: ["Annotate simple reflex pathway diagrams."],
    examCommandWords: ["describe", "explain", "compare"],
    linkedTopics: ["Hormonal control", "Homeostasis"],
  }),
  bioRow({
    id: "ocr-bio-hormonal-control",
    topic: "Hormonal control",
    specCode: "OCR GCSE Biology — Hormonal control",
    title: "Hormonal control",
    tier: "both",
    requiredContent: [
      "Hormones from endocrine glands travel in blood to target organs carrying receptors.",
      "Blood glucose: insulin lowers concentration; glucagon raises it (mechanism at GCSE depth per specification).",
      "Reproductive hormones (e.g. FSH, LH, oestrogen, progesterone) regulate the menstrual cycle overview.",
    ],
    requiredSkills: ["Compare nervous vs hormonal control using speed and duration."],
    examCommandWords: ["explain", "describe"],
    linkedTopics: ["Homeostasis", "Inheritance"],
  }),
  bioRow({
    id: "ocr-bio-inheritance",
    topic: "Inheritance",
    specCode: "OCR GCSE Biology — Inheritance",
    title: "Inheritance",
    tier: "both",
    requiredContent: [
      "Genes, alleles, and chromosomes; dominant and recessive inheritance patterns.",
      "Meiosis produces haploid gametes; fertilisation restores diploid number.",
      "Monohybrid crosses with Punnett squares; interpret family pedigrees at simple level.",
    ],
    requiredSkills: ["Predict phenotype probabilities from given parental genotypes."],
    examCommandWords: ["calculate", "explain", "predict"],
    linkedTopics: ["Variation and evolution", "Cell differentiation"],
  }),
  bioRow({
    id: "ocr-bio-variation-evolution",
    topic: "Variation and evolution",
    specCode: "OCR GCSE Biology — Variation and evolution",
    title: "Variation and evolution",
    tier: "both",
    requiredContent: [
      "Genetic and environmental sources of variation act together on phenotype.",
      "Natural selection: heritable advantageous traits increase in frequency over generations.",
      "Evidence includes fossils, comparative anatomy, and molecular patterns; antibiotic resistance as rapid example.",
      "Selective breeding applies the same inheritance principles with human-chosen goals.",
    ],
    requiredSkills: ["Apply Darwin’s ideas to a novel scenario with variation and competition."],
    examCommandWords: ["explain", "evaluate"],
    linkedTopics: ["Inheritance", "Ecology"],
  }),
  bioRow({
    id: "ocr-bio-ecology",
    topic: "Ecology",
    specCode: "OCR GCSE Biology — Ecology",
    title: "Ecology",
    tier: "both",
    requiredContent: [
      "Levels of organisation: organism, population, community, ecosystem; abiotic and biotic factors.",
      "Food chains and webs; pyramids of number, biomass, or energy (interpretation as specified).",
      "Sampling techniques (e.g. quadrats, transects) estimate distribution and abundance.",
      "Nutrient cycles and human impacts on biodiversity at overview depth for OCR.",
    ],
    requiredSkills: ["Use simple field data to justify conclusions about population or distribution."],
    examCommandWords: ["describe", "explain", "evaluate"],
    linkedTopics: ["Photosynthesis", "Variation and evolution", "Transport in plants"],
  }),
];
