import { OFFICIAL_OCR_SOURCE_NOTE } from "./schema.js";

/**
 * @param {Omit<import("./schema.js").SpecTopicEntry, "board" | "subject" | "keyStage" | "qualification" | "qualificationType" | "route" | "sourceNote"> & { route?: import("./schema.js").SpecRoute }} p
 */
function chemRow(p) {
  const {
    id,
    topic,
    specCode,
    title,
    requiredContent,
    requiredSkills,
    requiredPracticals,
    commonMisconceptions,
    examCommandWords,
    linkedTopics,
    tier = "both",
    contentFlags = {},
    route = "chemistry",
  } = p;
  return {
    id,
    board: "OCR",
    subject: "Chemistry",
    keyStage: "KS4 - GCSE",
    qualification: "GCSE Chemistry",
    qualificationType: "single-science",
    tier,
    route,
    topic,
    specCode,
    title,
    requiredContent,
    requiredSkills: requiredSkills ?? [],
    requiredPracticals: requiredPracticals ?? [],
    commonMisconceptions: commonMisconceptions ?? [],
    examCommandWords: examCommandWords ?? [],
    linkedTopics: linkedTopics ?? [],
    contentFlags,
    sourceNote: OFFICIAL_OCR_SOURCE_NOTE,
  };
}

/** @type {import("./schema.js").SpecTopicEntry[]} */
export const ocrChemistryGcseSpecEntries = [
  chemRow({
    id: "ocr-chem-atomic-structure",
    topic: "Atomic structure",
    specCode: "OCR GCSE Chemistry — Atomic structure",
    title: "Atomic structure",
    requiredContent: [
      "Atoms have a nucleus (protons, neutrons) and electrons in shells; atomic number defines element identity.",
      "Electronic structure influences reactivity; relate shells to Group/Period trends for elements studied.",
      "Isotopes of an element differ in neutron number; relative atomic mass as weighted mean (conceptual).",
    ],
    requiredSkills: ["Write electron configurations for first 20 elements where examined."],
    examCommandWords: ["describe", "explain", "calculate"],
    linkedTopics: ["Periodic table", "Bonding", "Quantitative chemistry"],
  }),
  chemRow({
    id: "ocr-chem-periodic-table",
    topic: "Periodic table",
    specCode: "OCR GCSE Chemistry — Periodic table",
    title: "Periodic table",
    requiredContent: [
      "Elements ordered by atomic number; periods (rows) and groups (columns) show repeating chemical properties.",
      "Group 1 trends in reactivity; noble gases’ low reactivity linked to outer electron arrangement.",
      "Transition metals as block between Groups 2 and 3 at overview level (properties in outline only).",
    ],
    requiredSkills: ["Predict missing trend data from given Group examples."],
    examCommandWords: ["describe", "explain", "predict"],
    linkedTopics: ["Atomic structure", "Bonding", "Chemical changes"],
  }),
  chemRow({
    id: "ocr-chem-bonding",
    topic: "Bonding",
    specCode: "OCR GCSE Chemistry — Bonding",
    title: "Bonding",
    requiredContent: [
      "Ionic transfer yields oppositely charged ions in giant lattices with high melting points when bonding is strong.",
      "Covalent sharing forms molecules or giant structures (diamond, graphite, silica) with contrasting properties.",
      "Metallic bonding uses delocalised electrons; explains conductivity and malleability qualitatively.",
    ],
    requiredSkills: ["Draw dot-and-cross diagrams for specified species."],
    examCommandWords: ["describe", "explain", "compare"],
    linkedTopics: ["Atomic structure", "Organic chemistry", "Chemical changes"],
  }),
  chemRow({
    id: "ocr-chem-quantitative",
    topic: "Quantitative chemistry",
    specCode: "OCR GCSE Chemistry — Quantitative chemistry",
    title: "Quantitative chemistry",
    requiredContent: [
      "Relative formula mass and moles link mass to particle amount in balanced equations.",
      "Conservation of mass; balance symbol equations with state symbols where required.",
      "Calculate masses or moles in straightforward stoichiometry; percentage yield as outcomes vs theoretical.",
    ],
    requiredSkills: ["Use mole ratios from balanced equations for simple mass–mole problems."],
    examCommandWords: ["calculate", "determine"],
    linkedTopics: ["Chemical changes", "Rates of reaction", "Chemical analysis"],
  }),
  chemRow({
    id: "ocr-chem-chemical-changes",
    topic: "Chemical changes",
    specCode: "OCR GCSE Chemistry — Chemical changes",
    title: "Chemical changes",
    requiredContent: [
      "Reactivity series predicts displacement and metal extraction methods relative to carbon/electrolysis.",
      "Acids with metals, carbonates, and alkalis; neutralisation to salts with characteristic naming patterns.",
      "Oxidation and reduction defined by electron transfer or oxygen gain/loss at GCSE framing.",
    ],
    requiredSkills: ["Write balanced equations for specified reaction types."],
    examCommandWords: ["describe", "explain", "write"],
    linkedTopics: ["Energy changes", "Earth and atmosphere", "Using resources"],
  }),
  chemRow({
    id: "ocr-chem-energy-changes",
    topic: "Energy changes",
    specCode: "OCR GCSE Chemistry — Energy changes",
    title: "Energy changes",
    requiredContent: [
      "Exothermic vs endothermic reactions; bond breaking endothermic and bond making exothermic overall model.",
      "Reaction profiles show activation energy and overall energy change direction (qualitative/numeric as specified).",
      "Fuel cells and combustion compared for useful energy release and environmental considerations (overview).",
    ],
    requiredSkills: ["Interpret energy level diagrams for given reactions."],
    examCommandWords: ["explain", "describe"],
    linkedTopics: ["Chemical changes", "Rates of reaction", "Earth and atmosphere"],
  }),
  chemRow({
    id: "ocr-chem-rates",
    topic: "Rates of reaction",
    specCode: "OCR GCSE Chemistry — Rates of reaction",
    title: "Rates of reaction",
    requiredContent: [
      "Rate depends on collision frequency and successful collisions; temperature and concentration increase rate typically.",
      "Surface area and catalysts alter pathway (lower activation energy); catalyst unchanged in mass overall.",
      "Measure rate via gas volume, colour change, or mass loss in given practical contexts.",
    ],
    requiredSkills: ["Compare gradients on concentration–time or volume–time graphs."],
    examCommandWords: ["explain", "compare"],
    linkedTopics: ["Quantitative chemistry", "Energy changes"],
  }),
  chemRow({
    id: "ocr-chem-organic",
    topic: "Organic chemistry",
    specCode: "OCR GCSE Chemistry — Organic chemistry",
    title: "Organic chemistry",
    requiredContent: [
      "Alkanes, alkenes, alcohols, carboxylic acids at specification depth; functional groups link to reactivity.",
      "Fractional distillation of crude oil; cracking links chain length to demand for fuels and feedstock.",
      "Addition polymerisation from alkenes; repeat units represented at simple level.",
    ],
    requiredSkills: ["Name and draw molecules within the prescribed homologous series."],
    examCommandWords: ["draw", "describe", "explain"],
    linkedTopics: ["Chemical analysis", "Using resources"],
  }),
  chemRow({
    id: "ocr-chem-chemical-analysis",
    topic: "Chemical analysis",
    specCode: "OCR GCSE Chemistry — Chemical analysis",
    title: "Chemical analysis",
    requiredContent: [
      "Pure substances have sharp melting/boiling characteristics; formulations are useful mixtures.",
      "Chromatography separates components; Rf compares migration to a standard (interpret diagrams).",
      "Qualitative tests for ions, water, and gases as prescribed for OCR GCSE.",
    ],
    requiredSkills: ["Plan separation or identification steps for simple unknowns."],
    examCommandWords: ["describe", "explain"],
    linkedTopics: ["Quantitative chemistry", "Organic chemistry"],
  }),
  chemRow({
    id: "ocr-chem-earth-atmosphere",
    topic: "Earth and atmosphere",
    specCode: "OCR GCSE Chemistry — Earth and atmosphere",
    title: "Earth and atmosphere",
    requiredContent: [
      "Atmospheric composition today vs early Earth (overview); role of photosynthesis and geological processes.",
      "Greenhouse gases absorb infrared; enhanced greenhouse effect linked to measurable climate indicators (non-polemic).",
      "Pollutants from combustion: particulates, sulfur/nitrogen oxides, carbon monoxide—effects outlined at GCSE.",
    ],
    requiredSkills: ["Use data to justify a simple claim about emissions or composition."],
    examCommandWords: ["explain", "evaluate"],
    linkedTopics: ["Chemical changes", "Using resources"],
  }),
  chemRow({
    id: "ocr-chem-using-resources",
    topic: "Using resources",
    specCode: "OCR GCSE Chemistry — Using resources",
    title: "Using resources",
    requiredContent: [
      "Finite resources vs renewables; life-cycle thinking from extraction to disposal.",
      "Recycling metals and polymers reduces energy and raw-material demand with trade-offs.",
      "Potable water treatment stages; compare with desalination energy cost at qualitative level.",
    ],
    requiredSkills: ["Compare environmental impacts of two resource choices using specification language."],
    examCommandWords: ["evaluate", "describe"],
    linkedTopics: ["Earth and atmosphere", "Organic chemistry"],
  }),
];
