import { OFFICIAL_OCR_SOURCE_NOTE } from "./schema.js";

/**
 * @param {Omit<import("./schema.js").SpecTopicEntry, "board" | "subject" | "keyStage" | "qualification" | "qualificationType" | "sourceNote"> & { route: import("./schema.js").SpecRoute }} p
 */
function combinedRow(p) {
  const {
    id,
    route,
    topic,
    specCode,
    title,
    requiredContent,
    requiredSkills,
    requiredPracticals,
    commonMisconceptions,
    examCommandWords,
    linkedTopics,
    tier = "both",
    contentFlags = {},
  } = p;
  return {
    id,
    board: "OCR",
    subject: "Combined Science",
    keyStage: "KS4 - GCSE",
    qualification: "GCSE Combined Science",
    qualificationType: "combined-science",
    tier,
    route,
    topic,
    specCode,
    title,
    requiredContent,
    requiredSkills: requiredSkills ?? [],
    requiredPracticals: requiredPracticals ?? [],
    commonMisconceptions: commonMisconceptions ?? [],
    examCommandWords: examCommandWords ?? [],
    linkedTopics: linkedTopics ?? [],
    contentFlags,
    sourceNote: OFFICIAL_OCR_SOURCE_NOTE,
  };
}

/** @type {import("./schema.js").SpecTopicEntry[]} */
export const ocrCombinedScienceSpecEntries = [
  combinedRow({
    id: "ocr-comb-bio-cell-structure",
    route: "biology",
    topic: "Cell structure",
    specCode: "OCR GCSE Combined — Biology — Cell structure",
    title: "Cell structure",
    requiredContent: [
      "Compare eukaryotic animal, plant, and prokaryotic cells at GCSE breadth required for Combined Science.",
      "Relate organelles to basic function; understand typical sizes with simple prefix use.",
      "Recognise specialised cells as differentiated for role (overview).",
    ],
    requiredSkills: ["Label diagrams and explain one structural adaptation example."],
    examCommandWords: ["describe", "compare"],
    linkedTopics: ["Microscopy", "Transport in plants"],
  }),
  combinedRow({
    id: "ocr-comb-bio-microscopy",
    route: "biology",
    topic: "Microscopy",
    specCode: "OCR GCSE Combined — Biology — Microscopy",
    title: "Microscopy",
    requiredContent: [
      "Light vs electron microscopes compared for magnification and resolution (qualitative).",
      "Magnification calculations with consistent units.",
      "Produce clear labelled drawings from observations where assessed.",
    ],
    requiredSkills: ["Use magnification = image size ÷ real size in set problems."],
    examCommandWords: ["calculate", "describe"],
    linkedTopics: ["Cell structure"],
  }),
  combinedRow({
    id: "ocr-comb-bio-transport-plants",
    route: "biology",
    topic: "Transport in plants",
    specCode: "OCR GCSE Combined — Biology — Transport",
    title: "Transport in plants",
    requiredContent: [
      "Xylem transports water and minerals upward; driven by transpiration pull overview.",
      "Phloem distributes sugars between sources and sinks.",
      "Stomata and guard cells regulate water loss vs gas exchange.",
    ],
    requiredSkills: ["Interpret simple transpiration investigations."],
    examCommandWords: ["explain", "describe"],
    linkedTopics: ["Photosynthesis", "Ecology"],
  }),
  combinedRow({
    id: "ocr-comb-bio-communicable",
    route: "biology",
    topic: "Communicable diseases",
    specCode: "OCR GCSE Combined — Biology — Communicable diseases",
    title: "Communicable diseases",
    requiredContent: [
      "Pathogen types and transmission routes at Combined breadth.",
      "Public health: vaccination, hygiene, vectors—case studies as per specification.",
      "Read simple incidence data to describe a trend.",
    ],
    requiredSkills: ["Compare two control measures for different pathogen classes."],
    examCommandWords: ["describe", "evaluate"],
    linkedTopics: ["Bacterial diseases", "Viral diseases", "Human defence systems"],
  }),
  combinedRow({
    id: "ocr-comb-bio-bacterial-diseases",
    route: "biology",
    topic: "Bacterial diseases",
    specCode: "OCR GCSE Combined — Biology — Bacterial diseases",
    title: "Bacterial diseases",
    requiredContent: [
      "Bacteria as cellular pathogens with example diseases at specification scope.",
      "Antibiotics act on bacteria only; resistance as selection over time (overview).",
      "Prevention via hygiene, safe food practice, and appropriate treatment.",
    ],
    requiredSkills: ["Justify why antibiotics are not used for viral infections."],
    examCommandWords: ["explain", "describe"],
    linkedTopics: ["Communicable diseases", "Human defence systems"],
  }),
  combinedRow({
    id: "ocr-comb-bio-viral-diseases",
    route: "biology",
    topic: "Viral diseases",
    specCode: "OCR GCSE Combined — Biology — Viral diseases",
    title: "Viral diseases",
    requiredContent: [
      "Viral structure simple model; replication requires host machinery.",
      "Named examples and transmission routes as required for Combined.",
      "Vaccination and other prevention strategies.",
    ],
    requiredSkills: ["Contrast viral spread vs bacterial routes for one example each."],
    examCommandWords: ["describe", "explain"],
    linkedTopics: ["Communicable diseases", "Human defence systems"],
  }),
  combinedRow({
    id: "ocr-comb-bio-human-defence",
    route: "biology",
    topic: "Human defence systems",
    specCode: "OCR GCSE Combined — Biology — Defence",
    title: "Human defence systems",
    requiredContent: [
      "Barriers and non-specific responses limit entry and spread.",
      "White blood cells, antibodies, memory cells in specific immunity (conceptual).",
      "Vaccination primes immune memory.",
    ],
    requiredSkills: ["Sequence a simple immune response narrative suitable for Combined."],
    examCommandWords: ["describe", "explain"],
    linkedTopics: ["Viral diseases", "Bacterial diseases"],
  }),
  combinedRow({
    id: "ocr-comb-bio-photosynthesis",
    route: "biology",
    topic: "Photosynthesis",
    specCode: "OCR GCSE Combined — Biology — Photosynthesis",
    title: "Photosynthesis",
    requiredContent: [
      "Light energy converted to chemical energy in glucose; occurs in chloroplasts.",
      "Limiting factors alter rate—interpret basic graphs.",
      "Inverse qualitative link to respiration over a day in plants (overview).",
    ],
    requiredSkills: ["Explain one limiting-factor result from given experimental data."],
    examCommandWords: ["explain", "describe"],
    linkedTopics: ["Respiration", "Transport in plants"],
  }),
  combinedRow({
    id: "ocr-comb-bio-respiration",
    route: "biology",
    topic: "Respiration",
    specCode: "OCR GCSE Combined — Biology — Respiration",
    title: "Respiration",
    requiredContent: [
      "Aerobic respiration uses oxygen to release energy from glucose.",
      "Anaerobic routes in muscles and yeast summarised for Combined scope.",
      "Word equations and mitochondria role at appropriate depth.",
    ],
    requiredSkills: ["Compare aerobic vs anaerobic outcomes in human vs yeast contexts."],
    examCommandWords: ["compare", "explain"],
    linkedTopics: ["Photosynthesis", "Ecology"],
  }),
  combinedRow({
    id: "ocr-comb-bio-homeostasis",
    route: "biology",
    topic: "Homeostasis",
    specCode: "OCR GCSE Combined — Biology — Homeostasis",
    title: "Homeostasis",
    requiredContent: [
      "Stable internal environment despite external change; receptors and effectors in loop models.",
      "Examples: temperature and blood glucose regulated via negative feedback (overview).",
    ],
    requiredSkills: ["Outline one feedback loop with named stimulus and response."],
    examCommandWords: ["explain", "describe"],
    linkedTopics: ["Inheritance"],
  }),
  combinedRow({
    id: "ocr-comb-bio-inheritance",
    route: "biology",
    topic: "Inheritance",
    specCode: "OCR GCSE Combined — Biology — Inheritance",
    title: "Inheritance",
    requiredContent: [
      "Genes, alleles, chromosomes; dominance at monohybrid level.",
      "Mitosis vs meiosis outcomes in broad terms for gamete formation.",
      "Construct and interpret basic Punnett squares.",
    ],
    requiredSkills: ["Predict phenotypic ratios from parental genotypes."],
    examCommandWords: ["calculate", "predict"],
    linkedTopics: ["Ecology", "Homeostasis"],
  }),
  combinedRow({
    id: "ocr-comb-bio-ecology",
    route: "biology",
    topic: "Ecology",
    specCode: "OCR GCSE Combined — Biology — Ecology",
    title: "Ecology",
    requiredContent: [
      "Abiotic and biotic factors; food chains and simple webs.",
      "Pyramids of number or biomass as specified; interpret energy transfer inefficiencies qualitatively.",
      "Human impacts on habitats (pollution, land use) at Combined depth.",
    ],
    requiredSkills: ["Use simple sampling reasoning from given methods."],
    examCommandWords: ["describe", "evaluate"],
    linkedTopics: ["Photosynthesis", "Transport in plants"],
  }),

  combinedRow({
    id: "ocr-comb-chem-atomic-structure",
    route: "chemistry",
    topic: "Atomic structure",
    specCode: "OCR GCSE Combined — Chemistry — Atomic structure",
    title: "Atomic structure",
    requiredContent: [
      "Subatomic particles and their charges; electronic structure outlines reactivity.",
      "Isotopes and relative atomic mass idea without heavy maths beyond specification.",
    ],
    requiredSkills: ["Deduce electron arrangements for early elements."],
    examCommandWords: ["describe", "explain"],
    linkedTopics: ["Bonding", "Quantitative chemistry"],
  }),
  combinedRow({
    id: "ocr-comb-chem-bonding",
    route: "chemistry",
    topic: "Bonding",
    specCode: "OCR GCSE Combined — Chemistry — Bonding",
    title: "Bonding",
    requiredContent: [
      "Ionic, covalent, metallic models compared using typical examples.",
      "Relate bonding and structure to selected bulk properties (melting, conductivity) as examined.",
    ],
    requiredSkills: ["Infer bonding type from position in periodic table for simple cases."],
    examCommandWords: ["explain", "compare"],
    linkedTopics: ["Atomic structure", "Chemical changes"],
  }),
  combinedRow({
    id: "ocr-comb-chem-quantitative",
    route: "chemistry",
    topic: "Quantitative chemistry",
    specCode: "OCR GCSE Combined — Chemistry — Quantitative",
    title: "Quantitative chemistry",
    requiredContent: [
      "Relative formula mass and the mole concept applied to straightforward reactions.",
      "Conservation of mass; balanced equations with state symbols when requested.",
    ],
    requiredSkills: ["Carry out prescribed mass–mole calculations."],
    examCommandWords: ["calculate"],
    linkedTopics: ["Chemical changes", "Rates of reaction"],
  }),
  combinedRow({
    id: "ocr-comb-chem-chemical-changes",
    route: "chemistry",
    topic: "Chemical changes",
    specCode: "OCR GCSE Combined — Chemistry — Chemical changes",
    title: "Chemical changes",
    requiredContent: [
      "Reactivity trends and extraction ideas at Combined depth.",
      "Acid–base and carbonate reactions producing salts.",
      "Redox terminology as specified for Combined.",
    ],
    requiredSkills: ["Write word or symbol equations for set contexts."],
    examCommandWords: ["describe", "write"],
    linkedTopics: ["Energy changes", "Earth and atmosphere"],
  }),
  combinedRow({
    id: "ocr-comb-chem-energy-changes",
    route: "chemistry",
    topic: "Energy changes",
    specCode: "OCR GCSE Combined — Chemistry — Energy changes",
    title: "Energy changes",
    requiredContent: [
      "Exothermic vs endothermic; simple reaction profiles.",
      "Bond breaking/making qualitative link to overall energy change.",
    ],
    requiredSkills: ["Read energy-level diagrams to classify reactions."],
    examCommandWords: ["explain"],
    linkedTopics: ["Chemical changes", "Rates of reaction"],
  }),
  combinedRow({
    id: "ocr-comb-chem-rates",
    route: "chemistry",
    topic: "Rates of reaction",
    specCode: "OCR GCSE Combined — Chemistry — Rates",
    title: "Rates of reaction",
    requiredContent: [
      "Factors affecting collision rate and successful collisions.",
      "Catalyst action in outline.",
      "Measure rate using specified practical indicators.",
    ],
    requiredSkills: ["Compare initial rates from simple graphs."],
    examCommandWords: ["explain", "compare"],
    linkedTopics: ["Quantitative chemistry"],
  }),
  combinedRow({
    id: "ocr-comb-chem-organic",
    route: "chemistry",
    topic: "Organic chemistry",
    specCode: "OCR GCSE Combined — Chemistry — Organic",
    title: "Organic chemistry",
    requiredContent: [
      "Hydrocarbons and key functional groups within Combined list.",
      "Fractional distillation and cracking concepts.",
      "Simple polymer ideas from alkenes.",
    ],
    requiredSkills: ["Recognise structural patterns in prescribed molecules."],
    examCommandWords: ["describe", "draw"],
    linkedTopics: ["Chemical analysis", "Using resources"],
  }),
  combinedRow({
    id: "ocr-comb-chem-chemical-analysis",
    route: "chemistry",
    topic: "Chemical analysis",
    specCode: "OCR GCSE Combined — Chemistry — Analysis",
    title: "Chemical analysis",
    requiredContent: [
      "Chromatography and Rf basics.",
      "Tests for gases and ions as listed for Combined.",
    ],
    requiredSkills: ["Propose a test sequence for a simple unknown."],
    examCommandWords: ["describe"],
    linkedTopics: ["Organic chemistry"],
  }),
  combinedRow({
    id: "ocr-comb-chem-earth-atmosphere",
    route: "chemistry",
    topic: "Earth and atmosphere",
    specCode: "OCR GCSE Combined — Chemistry — Earth and atmosphere",
    title: "Earth and atmosphere",
    requiredContent: [
      "Atmospheric change over geological time (overview).",
      "Greenhouse effect and human-linked emissions at GCSE balance.",
      "Pollutants from fuels: environmental and health effects outlined.",
    ],
    requiredSkills: ["Use evidence snippets to support a cautious conclusion about emissions."],
    examCommandWords: ["explain", "evaluate"],
    linkedTopics: ["Chemical changes", "Using resources"],
  }),
  combinedRow({
    id: "ocr-comb-chem-using-resources",
    route: "chemistry",
    topic: "Using resources",
    specCode: "OCR GCSE Combined — Chemistry — Resources",
    title: "Using resources",
    requiredContent: [
      "Finite resources, recycling, and sustainability trade-offs.",
      "Potable vs pure water; treatment stages summary.",
    ],
    requiredSkills: ["Compare two disposal or recycling routes qualitatively."],
    examCommandWords: ["evaluate"],
    linkedTopics: ["Earth and atmosphere"],
  }),

  combinedRow({
    id: "ocr-comb-phys-energy",
    route: "physics",
    topic: "Energy stores and transfers",
    specCode: "OCR GCSE Combined — Physics — Energy",
    title: "Energy stores and transfers",
    requiredContent: [
      "Identify and describe transfers between energy stores in prescribed contexts.",
      "Efficiency and wasted energy ideas suitable for Combined.",
    ],
    requiredSkills: ["Calculate efficiency in simple numerical cases."],
    examCommandWords: ["describe", "calculate"],
    linkedTopics: ["Electricity", "Particle model"],
  }),
  combinedRow({
    id: "ocr-comb-phys-electricity",
    route: "physics",
    topic: "Electricity",
    specCode: "OCR GCSE Combined — Physics — Electricity",
    title: "Electricity",
    requiredContent: [
      "Series and parallel rules; Ohm’s law for many components.",
      "Domestic electricity safety basics; power and energy calculations.",
    ],
    requiredSkills: ["Solve for I, V, R in simple networks."],
    examCommandWords: ["calculate", "explain"],
    linkedTopics: ["Magnetism and electromagnetism"],
  }),
  combinedRow({
    id: "ocr-comb-phys-particle-model",
    route: "physics",
    topic: "Particle model",
    specCode: "OCR GCSE Combined — Physics — Particle model",
    title: "Particle model",
    requiredContent: [
      "States of matter and changes of state from particle viewpoint.",
      "Specific heat and latent heat at Combined equation depth.",
      "Gas pressure from particle collisions (qualitative).",
    ],
    requiredSkills: ["Apply thermal equations in set problems."],
    examCommandWords: ["explain", "calculate"],
    linkedTopics: ["Energy stores and transfers", "Forces"],
  }),
  combinedRow({
    id: "ocr-comb-phys-radioactivity",
    route: "physics",
    topic: "Radioactivity",
    specCode: "OCR GCSE Combined — Physics — Radioactivity",
    title: "Radioactivity",
    requiredContent: [
      "Nuclear structure; isotopes and instability.",
      "Ionising radiation types compared; half-life from graphs.",
      "Safe use and applications overview.",
    ],
    requiredSkills: ["Interpret decay or half-life data at Combined level."],
    examCommandWords: ["describe", "explain"],
    linkedTopics: ["Forces", "Waves"],
  }),
  combinedRow({
    id: "ocr-comb-phys-forces",
    route: "physics",
    topic: "Forces",
    specCode: "OCR GCSE Combined — Physics — Forces",
    title: "Forces",
    requiredContent: [
      "Resultant force and motion links; Newton’s laws at Combined depth.",
      "Moments, pressure, Hooke’s law basics.",
      "Graph skills for motion.",
    ],
    requiredSkills: ["Use F = ma where examined; interpret motion graphs."],
    examCommandWords: ["calculate", "describe"],
    linkedTopics: ["Energy stores and transfers", "Waves"],
  }),
  combinedRow({
    id: "ocr-comb-phys-waves",
    route: "physics",
    topic: "Waves",
    specCode: "OCR GCSE Combined — Physics — Waves",
    title: "Waves",
    requiredContent: [
      "Wave types and v = fλ.",
      "Electromagnetic spectrum uses/risks; sound basics.",
    ],
    requiredSkills: ["Perform simple wave speed calculations."],
    examCommandWords: ["describe", "calculate"],
    linkedTopics: ["Radioactivity"],
  }),
  combinedRow({
    id: "ocr-comb-phys-magnetism",
    route: "physics",
    topic: "Magnetism and electromagnetism",
    specCode: "OCR GCSE Combined — Physics — Magnetism",
    title: "Magnetism and electromagnetism",
    requiredContent: [
      "Fields from magnets and currents; basic rules as specified.",
      "Motor and simple generator principles qualitatively.",
    ],
    requiredSkills: ["Apply Fleming’s left-hand rule to predict force direction when given."],
    examCommandWords: ["explain"],
    linkedTopics: ["Electricity"],
  }),
];
