/**
 * Reusable Question Bank Audit — writes docs from service data.
 * Uses backend/services/questionBankAuditService.js as single source of truth.
 * Caller must ensure mongoose is connected.
 */
const path = require("path");
const fs = require("fs");
const { runQuestionBankAudit } = require("../../services/questionBankAuditService");
const { getTaxonomyBySpecKey } = require("../../utils/topicTaxonomy");
const normalizeSpecKey = require("../../utils/normalizeSpecKey");
const { specKeyForFilename } = require("../../utils/normalizeSpecKey");

/** Internal specKey may be hyphen or underscore; for filenames use hyphen so docs viewer finds them. */
function safeSpecKeyForFilename(specKey) {
  if (!specKey || typeof specKey !== "string") return "unknown";
  const normalized = normalizeSpecKey(specKey);
  const hyphen = specKeyForFilename(normalized);
  return hyphen || String(specKey).replace(/[/:]/g, "-").trim() || "unknown";
}

function getDocsOutDir() {
  const repoRoot = path.resolve(__dirname, "..", "..", "..");
  return path.join(repoRoot, "frontend", "public", "docs");
}

function ensureDir(dir) {
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
}

/** Row accessors for both service shape (counts.*, mainTopicTitle) and legacy (mcq, mainTopic) */
function rowMainTopic(r) {
  return r.mainTopicTitle ?? r.mainTopic;
}
function rowSubTopic(r) {
  return r.subTopicTitle ?? r.subTopic;
}
function rowMcq(r) {
  return r.counts?.mcq ?? r.mcq ?? 0;
}
function rowShort(r) {
  return r.counts?.short ?? r.short ?? 0;
}
function rowFlashcards(r) {
  return r.counts?.flashcards ?? r.flashcards ?? 0;
}
function rowExamQuestions(r) {
  return r.counts?.examQuestions ?? r.examQuestions ?? 0;
}
function rowRecall(r) {
  return r.recall ?? 0;
}
function rowApplication(r) {
  return r.application ?? 0;
}
function rowMisconceptionTag(r) {
  return r.misconceptionTag ?? 0;
}

/**
 * Run audit via service and write QUESTION_BANK_AUDIT_<specKey>.md + SPRINT_ORDER_<specKey>.md.
 * @param {{ specKey: string, outDir?: string, publicDocsDir?: string }} options
 *   - outDir: repo root docs/ (or custom)
 *   - publicDocsDir: if set, also write to this path (frontend/public/docs for docs viewer)
 * @returns {Promise<{ rows: Array, sprintOrder: Array }>}
 */
async function runQuestionBankAuditAndWrite({ specKey, outDir = "docs", publicDocsDir: explicitPublicDocsDir } = {}) {
  const { rows, summary } = await runQuestionBankAudit({ specKey });
  const taxonomy = getTaxonomyBySpecKey(specKey);
  const scopeLine = [
    `- **Subject:** ${taxonomy?.subject || "Unknown"}`,
    taxonomy?.level ? `  \n- **Level:** ${taxonomy.level}` : "",
    taxonomy?.examBoard ? `  \n- **Exam board:** ${taxonomy.examBoard}` : "",
  ]
    .filter(Boolean)
    .join("");

  const statusOrder = { EMPTY: 0, GAP: 1, OK: 2 };
  const sprintOrder = [...rows].sort((a, b) => {
    const sa = statusOrder[a.status] ?? 2;
    const sb = statusOrder[b.status] ?? 2;
    if (sa !== sb) return sa - sb;
    return (a.topicIndex ?? 0) - (b.topicIndex ?? 0);
  });

  const repoRoot = path.resolve(__dirname, "..", "..", "..");
  const resolvedOutDir = path.isAbsolute(outDir) ? outDir : path.join(repoRoot, outDir);
  ensureDir(resolvedOutDir);

  const fileKey = safeSpecKeyForFilename(specKey);
  const opts = { encoding: "utf8" };

  const auditContent = buildAuditMdContent(specKey, scopeLine, rows);
  const sprintContent = buildSprintOrderMdContent(specKey, sprintOrder, rows);

  const auditPath = path.join(resolvedOutDir, `QUESTION_BANK_AUDIT_${fileKey}.md`);
  const sprintPath = path.join(resolvedOutDir, `SPRINT_ORDER_${fileKey}.md`);
  fs.writeFileSync(auditPath, auditContent, opts);
  fs.writeFileSync(sprintPath, sprintContent, opts);

  const publicDocsDir = explicitPublicDocsDir || getDocsOutDir();
  ensureDir(publicDocsDir);
  const auditPublicPath = path.join(publicDocsDir, `QUESTION_BANK_AUDIT_${fileKey}.md`);
  const sprintPublicPath = path.join(publicDocsDir, `SPRINT_ORDER_${fileKey}.md`);
  fs.writeFileSync(auditPublicPath, auditContent, opts);
  fs.writeFileSync(sprintPublicPath, sprintContent, opts);
  if (process.env.NODE_ENV !== "test") {
    console.log("[audit] Wrote to frontend/public/docs:", auditPublicPath, sprintPublicPath);
  }

  return { rows, sprintOrder };
}

function buildAuditMdContent(specKey, scopeLine, rows) {
  const lines = [
    `# Question Bank Audit — ${specKey}`,
    "",
    `Generated by \`runQuestionBankAudit({ specKey: "${specKey}" })\`. Re-run the script to refresh.`,
    "",
    "## Scope",
    scopeLine,
    "- **Collections:** TopicQuizQuestion, TopicFlashcard, ExamQuestion, PastPaperQuestion (platform-wide counts)",
    "",
    "## Status rules",
    "- **OK** = usable starter bank (≥10 MCQs, ≥5 short-answer, ≥5 flashcards)",
    "- **GAP** = partially usable; needs topping up",
    "- **EMPTY** = no questions or flashcards; must be built",
    "",
    "## Definition of Done (DoD)",
    "Sub-topic is **DONE** when: ≥10 MCQs, ≥5 short-answer, and ≥1 question tagged for misconception/distractor.",
    "Spec coverage is not auto-checked; verify manually.",
    "",
    "---",
    "",
    "| Subject | Main topic | Sub-topic | MCQ | Short | Flashcards | Exam Qs | Recall | Application | Misconception tag | Status | DoD |",
    "|---------|------------|-----------|-----|-------|------------|--------|--------|--------------|-------------------|--------|-----|",
  ];

  for (const r of rows) {
    lines.push(
      `| ${r.subject} | ${rowMainTopic(r)} | ${rowSubTopic(r)} | ${rowMcq(r)} | ${rowShort(r)} | ${rowFlashcards(r)} | ${rowExamQuestions(r)} | ${rowRecall(r)} | ${rowApplication(r)} | ${rowMisconceptionTag(r)} | ${r.status} | ${r.dod} |`
    );
  }

  const emptyCount = rows.filter((x) => x.status === "EMPTY").length;
  const gapCount = rows.filter((x) => x.status === "GAP").length;
  const okCount = rows.filter((x) => x.status === "OK").length;
  const doneCount = rows.filter((x) => x.dod === "DONE").length;
  lines.push("");
  lines.push("## Summary");
  lines.push(`- **EMPTY:** ${emptyCount}  \n- **GAP:** ${gapCount}  \n- **OK:** ${okCount}  \n- **DoD DONE:** ${doneCount}  \n- **Total sub-topics:** ${rows.length}`);
  lines.push("");
  return lines.join("\n");
}

function buildSprintOrderMdContent(specKey, sprintOrder, rows) {
  return writeSprintOrderMd(undefined, specKey, sprintOrder, rows);
}

function writeSprintOrderMd(_filePath, specKey, sprintOrder, rows) {
  const lines = [
    `# Sprint Order — ${specKey}`,
    "",
    `Generated by \`runQuestionBankAudit({ specKey: "${specKey}" })\`. Build question banks in this order.`,
    "",
    "## Priority",
    "1. **EMPTY** sub-topics first",
    "2. Then **GAP**",
    "3. Then **OK** (top-up only if needed)",
    "Within each group, syllabus order.",
    "",
    "---",
    "",
    "| # | Subject | Main topic | Sub-topic | Status | DoD |",
    "|---|---------|------------|-----------|--------|-----|",
  ];

  sprintOrder.forEach((r, i) => {
    lines.push(`| ${i + 1} | ${r.subject} | ${rowMainTopic(r)} | ${rowSubTopic(r)} | ${r.status} | ${r.dod} |`);
  });

  const emptyCount = rows.filter((x) => x.status === "EMPTY").length;
  const gapCount = rows.filter((x) => x.status === "GAP").length;
  lines.push("");
  lines.push("## Sprint focus");
  lines.push("Complete **EMPTY** and **GAP** sub-topics first.");
  lines.push(`- **EMPTY to build:** ${emptyCount}`);
  lines.push(`- **GAP to top up:** ${gapCount}`);
  lines.push("");
  lines.push("Do not start lessons until **Stage 1 (Core recall)** question banks are DONE for the topic (see Sprint Plan DoD).");
  lines.push("");
  lines.push("## What to ignore for now");
  lines.push("- Sub-topics already **OK** unless you are refining quality.");
  lines.push("- Creating new lessons before question banks meet the Definition of Done.");
  lines.push("");
  lines.push("## Good enough");
  lines.push("Sub-topics marked **OK** are usable as starter banks. Those marked **DoD DONE** meet the full Definition of Done and are safe for auto-attach and reuse.");
  lines.push("");
  return lines.join("\n");
}

module.exports = {
  runQuestionBankAuditAndWrite,
  safeSpecKeyForFilename,
};
