#!/usr/bin/env node
/* eslint-disable no-console */
/**
 * Export Subject → Main Topic → Sub-topic list from backend/config/*_topics.json.
 * Outputs: docs/TAXONOMY_TOPIC_LIST.md, docs/TAXONOMY_TOPIC_LIST.csv
 *
 * Run from repo root or backend:
 *   cd backend && npm run export:taxonomy-topics
 */
const fs = require("fs");
const path = require("path");

const CONFIG_DIR = path.join(__dirname, "..", "config");
const DOCS_DIR = path.join(__dirname, "..", "..", "docs");
const MD_PATH = path.join(DOCS_DIR, "TAXONOMY_TOPIC_LIST.md");
const CSV_PATH = path.join(DOCS_DIR, "TAXONOMY_TOPIC_LIST.csv");

/** Derive specKey from filename e.g. aqa_gcse_biology_topics.json → aqa-gcse-biology */
function specKeyFromFilename(filePath) {
  const base = path.basename(filePath, path.extname(filePath));
  const withoutSuffix = base.replace(/_topics$/, "");
  return withoutSuffix.replace(/_/g, "-").toLowerCase();
}

function getTopicFiles() {
  if (!fs.existsSync(CONFIG_DIR)) return [];
  return fs
    .readdirSync(CONFIG_DIR)
    .filter((f) => f.endsWith("_topics.json"))
    .sort()
    .map((f) => path.join(CONFIG_DIR, f));
}

function readJson(filePath) {
  const raw = fs.readFileSync(filePath, "utf8");
  return JSON.parse(raw);
}

/**
 * Traverse taxonomy in-order; emit one row per LEAF topic.
 * Structure: { subject, examBoard, level, specKey?, units: [ { unit, key?, topics: [ { topic, key } ] } ] }
 */
function collectLeafRows(filePath, data, fileLabel) {
  const specKey =
    typeof data.specKey === "string" && data.specKey.trim()
      ? data.specKey.trim()
      : specKeyFromFilename(filePath);
  const subject =
    typeof data.subject === "string" && data.subject.trim() ? data.subject.trim() : "Unknown";
  const units = Array.isArray(data.units) ? data.units : [];
  const rows = [];

  for (const unit of units) {
    const mainTopicTitle =
      typeof unit.unit === "string" && unit.unit.trim() ? unit.unit.trim() : null;
    const topics = Array.isArray(unit.topics) ? unit.topics : [];

    for (const t of topics) {
      const leafTitle = typeof t.topic === "string" && t.topic.trim() ? t.topic.trim() : null;
      const topicSlug = typeof t.key === "string" && t.key.trim() ? t.key.trim() : null;

      if (!leafTitle || !topicSlug) {
        console.warn(
          `[${fileLabel}] Skipping topic missing title or key: unit="${mainTopicTitle}" topic=${JSON.stringify(t)}`
        );
        continue;
      }

      const topicKey = `${specKey}:${topicSlug}`;
      const pathTitles = mainTopicTitle ? `${mainTopicTitle} > ${leafTitle}` : leafTitle;

      rows.push({
        subject,
        specKey,
        mainTopicTitle: mainTopicTitle || "",
        leafTopicTitle: leafTitle,
        topicSlug,
        topicKey,
        pathTitles,
      });
    }
  }

  return rows;
}

function escapeCsvCell(s) {
  const str = String(s ?? "");
  if (str.includes(",") || str.includes('"') || str.includes("\n") || str.includes("\r")) {
    return `"${str.replace(/"/g, '""')}"`;
  }
  return str;
}

function writeCsv(allRows) {
  const header = "subject,specKey,mainTopicTitle,leafTopicTitle,topicSlug,topicKey,pathTitles";
  const lines = [header, ...allRows.map((r) => [r.subject, r.specKey, r.mainTopicTitle, r.leafTopicTitle, r.topicSlug, r.topicKey, r.pathTitles].map(escapeCsvCell).join(","))];
  fs.writeFileSync(CSV_PATH, lines.join("\n"), "utf8");
  console.log(`Wrote ${CSV_PATH} (${allRows.length} rows)`);
}

function writeMarkdown(allRows, subjectNotPresent) {
  const bySubject = new Map();
  for (const r of allRows) {
    if (!bySubject.has(r.subject)) bySubject.set(r.subject, []);
    bySubject.get(r.subject).push(r);
  }

  const priorityOrder = ["Biology", "Chemistry", "Physics", "Mathematics", "Further Mathematics", "English Language", "English Literature"];
  const intro = [
    "# Taxonomy topic list (Subject → Main topic → Sub-topic)",
    "",
    "**Source:** Generated from `backend/config/*_topics.json`. Do not edit this file by hand.",
    "",
    "**Regenerate:** From repo root: `cd backend && npm run export:taxonomy-topics`",
    "",
  ];

  if (subjectNotPresent.length > 0) {
    intro.push("**Not present in config yet:** " + subjectNotPresent.join(", ") + "", "");
  }

  const sections = [];
  for (const subject of priorityOrder) {
    const rows = bySubject.get(subject);
    if (!rows || rows.length === 0) continue;

    const bySpec = new Map();
    for (const r of rows) {
      if (!bySpec.has(r.specKey)) bySpec.set(r.specKey, []);
      bySpec.get(r.specKey).push(r);
    }

    sections.push(`## ${subject}`);
    sections.push("");

    for (const [specKey, specRows] of bySpec) {
      sections.push(`### ${specKey}`);
      sections.push("");
      sections.push("| Main topic | Sub-topic (leaf) | topicKey | path |");
      sections.push("|------------|------------------|----------|------|");
      for (const r of specRows) {
        sections.push(
          `| ${r.mainTopicTitle.replace(/\|/g, "\\|")} | ${r.leafTopicTitle.replace(/\|/g, "\\|")} | \`${r.topicKey}\` | ${r.pathTitles.replace(/\|/g, "\\|")} |`
        );
      }
      sections.push("");
    }
  }

  const otherSubjects = [...bySubject.keys()].filter((s) => !priorityOrder.includes(s));
  for (const subject of otherSubjects.sort()) {
    const rows = bySubject.get(subject);
    const bySpec = new Map();
    for (const r of rows) {
      if (!bySpec.has(r.specKey)) bySpec.set(r.specKey, []);
      bySpec.get(r.specKey).push(r);
    }
    sections.push(`## ${subject}`);
    sections.push("");
    for (const [specKey, specRows] of bySpec) {
      sections.push(`### ${specKey}`);
      sections.push("");
      sections.push("| Main topic | Sub-topic (leaf) | topicKey | path |");
      sections.push("|------------|------------------|----------|------|");
      for (const r of specRows) {
        sections.push(
          `| ${r.mainTopicTitle.replace(/\|/g, "\\|")} | ${r.leafTopicTitle.replace(/\|/g, "\\|")} | \`${r.topicKey}\` | ${r.pathTitles.replace(/\|/g, "\\|")} |`
        );
      }
      sections.push("");
    }
  }

  const out = intro.join("\n") + "\n" + sections.join("\n");
  fs.writeFileSync(MD_PATH, out, "utf8");
  console.log(`Wrote ${MD_PATH}`);
}

function main() {
  const files = getTopicFiles();
  if (files.length === 0) {
    console.error("No *_topics.json files found in backend/config");
    process.exit(1);
  }

  const allRows = [];
  for (const filePath of files) {
    const fileLabel = path.basename(filePath);
    let data;
    try {
      data = readJson(filePath);
    } catch (e) {
      console.error(`${fileLabel}: ${e.message}`);
      process.exit(1);
    }
    const rows = collectLeafRows(filePath, data, fileLabel);
    allRows.push(...rows);
  }

  if (!fs.existsSync(DOCS_DIR)) {
    fs.mkdirSync(DOCS_DIR, { recursive: true });
  }

  const expectedSubjects = ["Biology", "Chemistry", "Physics", "Maths", "English"];
  const subjectsPresent = [...new Set(allRows.map((r) => r.subject))];
  const hasMaths = subjectsPresent.some((s) => s === "Mathematics" || s.includes("Math"));
  const hasEnglish = subjectsPresent.some((s) => s.includes("English"));
  const subjectNotPresent = expectedSubjects.filter((s) => {
    if (s === "Biology") return !subjectsPresent.includes("Biology");
    if (s === "Chemistry") return !subjectsPresent.includes("Chemistry");
    if (s === "Physics") return !subjectsPresent.includes("Physics");
    if (s === "Maths") return !hasMaths;
    if (s === "English") return !hasEnglish;
    return true;
  });

  writeCsv(allRows);
  writeMarkdown(allRows, subjectNotPresent);
}

main();
