/**
 * Teacher Brain — Phase 1 entry (analysis only).
 */

const { runTeacherBrain } = require("./TeacherBrainEngine");
const { buildLessonTruth } = require("./lessonTruth/buildLessonTruth");
const {
  injectDiagramAndActivityBriefs,
  formatDiagramBrief,
  formatDragDropBrief,
  formatTextMatchBrief,
  formatTextToImageBrief,
  formatImageDropZonesBrief,
  formatStepByStepBrief,
  resolveDragDropActivityLayout,
  BRIEF_MARKER,
} = require("./diagramBriefInjector");
const { detectDragDropActivityLayout } = require("./dragDropActivityLayout");
const { formatDragDropImageDesignRequirements } = require("./dragDropVisualContract");
const { resolveInteractiveDiagramTopicKind } = require("./interactiveDiagramTopicKind");
const {
  getInteractiveDiagramPlansForTopicKind,
  formatInteractiveDiagramTopicBrief,
} = require("./interactiveDiagramTopicSpecs");
const { resolveInteractiveSequenceTopicKind } = require("./interactiveSequenceTopicKind");
const { formatInteractiveSequenceTopicBrief } = require("./interactiveSequenceTopicSpecs");
const {
  generateTeacherBrainBrief,
  formatTeacherBrainBriefNote,
  normalizeActivityType,
  isGenericPlaceholder,
  extractLessonVocabulary,
  collectSurroundingBlocks,
  pairsAreGeneric,
} = require("./briefs");

module.exports = {
  runTeacherBrain,
  buildLessonTruth,
  injectDiagramAndActivityBriefs,
  formatDiagramBrief,
  formatDragDropBrief,
  formatTextMatchBrief,
  formatTextToImageBrief,
  formatImageDropZonesBrief,
  formatStepByStepBrief,
  resolveDragDropActivityLayout,
  detectDragDropActivityLayout,
  BRIEF_MARKER,
  formatDragDropImageDesignRequirements,
  resolveInteractiveDiagramTopicKind,
  getInteractiveDiagramPlansForTopicKind,
  formatInteractiveDiagramTopicBrief,
  resolveInteractiveSequenceTopicKind,
  formatInteractiveSequenceTopicBrief,
  generateTeacherBrainBrief,
  formatTeacherBrainBriefNote,
  normalizeActivityType,
  isGenericPlaceholder,
  extractLessonVocabulary,
  collectSurroundingBlocks,
  pairsAreGeneric,
  extractCoreConcepts: require("./conceptExtractor").extractCoreConcepts,
  planMisconceptions: require("./misconceptionEngine").planMisconceptions,
  planRequiredDiagrams: require("./diagramPlanner").planRequiredDiagrams,
  planActivityRecommendations: require("./activityPlanner").planActivityRecommendations,
  planExamTargets: require("./examPlanner").planExamTargets,
  planRetrieval: require("./retrievalPlanner").planRetrieval,
  buildLessonCoverageMap: require("./lessonCoverageIntelligence").buildLessonCoverageMap,
  checkCoverageBeforeGeneration: require("./lessonCoverageIntelligence").checkCoverageBeforeGeneration,
  formatCoverageMapForPrompt: require("./lessonCoverageIntelligence").formatCoverageMapForPrompt,
  COGNITIVE_SKILLS: require("./lessonCoverageIntelligence").COGNITIVE_SKILLS,
  createCoverageGateFromLesson: require("./coverageGatedGeneration").createCoverageGateFromLesson,
  createCoverageGenerationGate: require("./coverageGatedGeneration").createCoverageGenerationGate,
  planCoverageGatedQuestion: require("./coverageGatedGeneration").planCoverageGatedQuestion,
  planCoverageGatedQuestionBatch: require("./coverageGatedGeneration").planCoverageGatedQuestionBatch,
  formatCoveragePlanForPrompt: require("./coverageGatedGeneration").formatCoveragePlanForPrompt,
  attachCoverageMetadata: require("./coverageGatedGeneration").attachCoverageMetadata,
  prependCoverageDirectiveToPrompt: require("./coverageGatedGeneration").prependCoverageDirectiveToPrompt,
  buildOneShotLessonCoveragePlanAppendix: require("./oneShotLessonCoveragePlan").buildOneShotLessonCoveragePlanAppendix,
  mergeOneShotCoveragePlanIntoInstructions: require("./oneShotLessonCoveragePlan").mergeOneShotCoveragePlanIntoInstructions,
  buildLessonCoverageReview: require("./lessonCoverageReview").buildLessonCoverageReview,
  resolveSubTopicProfile: require("./subTopicProfiles").resolveSubTopicProfile,
  listProfileConcepts: require("./subTopicProfiles").listProfileConcepts,
  NERVOUS_SYSTEM_STRUCTURE_PROFILE: require("./subTopicProfiles").NERVOUS_SYSTEM_STRUCTURE_PROFILE,
  classifyConcept: require("./subTopicBoundaryGuard").classifyConcept,
  validateGenerationSlot: require("./subTopicBoundaryGuard").validateGenerationSlot,
  validateBlockScope: require("./subTopicBoundaryGuard").validateBlockScope,
  scoreScopeContamination: require("./subTopicBoundaryGuard").scoreScopeContamination,
  getSubTopicBoundaryMode: require("./subTopicBoundaryGuard").getSubTopicBoundaryMode,
  isSubTopicBoundaryEnforcementEnabled: require("./subTopicBoundaryGuard").isSubTopicBoundaryEnforcementEnabled,
  buildSubTopicBoundaryContext: require("./subTopicBoundaryPlanning").buildSubTopicBoundaryContext,
  formatSubTopicBoundaryAppendix: require("./subTopicBoundaryPlanning").formatSubTopicBoundaryAppendix,
  buildBoundaryReviewFromLesson: require("./subTopicBoundaryPlanning").buildBoundaryReviewFromLesson,
  auditLessonBoundary: require("./lessonBoundaryAudit").auditLessonBoundary,
  boundaryAuditResponseMeta: require("./lessonBoundaryAudit").boundaryAuditResponseMeta,
  planBoundaryReplacements: require("./boundaryReplacementPlanner").planBoundaryReplacements,
  formatBoundaryReplacementAppendix: require("./boundaryReplacementPlanner").formatBoundaryReplacementAppendix,
  boundaryReplacementResponseMeta: require("./boundaryReplacementPlanner").boundaryReplacementResponseMeta,
  buildBoundaryReplacementFromLesson: require("./boundaryReplacementPlanner").buildBoundaryReplacementFromLesson,
  planBoundaryInteractionReplacements: require("./boundaryInteractionReplacementPlanner").planBoundaryInteractionReplacements,
  formatBoundaryInteractionReplacementAppendix: require("./boundaryInteractionReplacementPlanner").formatBoundaryInteractionReplacementAppendix,
  mergeInteractionPlanIntoReplacementPlan: require("./boundaryInteractionReplacementPlanner").mergeInteractionPlanIntoReplacementPlan,
  enforceObjectiveBoundaries: require("./objectiveBoundaryEnforcer").enforceObjectiveBoundaries,
  enforceObjectiveBoundariesOnDraft: require("./objectiveBoundaryEnforcer").enforceObjectiveBoundariesOnDraft,
  analyzeObjectiveBoundaryFromLesson: require("./objectiveBoundaryEnforcer").analyzeObjectiveBoundaryFromLesson,
  formatObjectiveBoundaryAppendix: require("./objectiveBoundaryEnforcer").formatObjectiveBoundaryAppendix,
  resolveConceptPriorityProfile: require("./conceptPriorityProfiles").resolveConceptPriorityProfile,
  isPriorityEngineEnabled: require("./conceptPriorityEngine").isPriorityEngineEnabled,
  getPriorityTier: require("./conceptPriorityEngine").getPriorityTier,
  scoreConceptPriority: require("./conceptPriorityEngine").scoreConceptPriority,
  sortConceptsByPriority: require("./conceptPriorityEngine").sortConceptsByPriority,
  formatConceptPriorityAppendix: require("./conceptPriorityEngine").formatConceptPriorityAppendix,
  buildConceptPriorityDistribution: require("./conceptPriorityEngine").buildConceptPriorityDistribution,
  resolvePedagogyProfile: require("./biologyPedagogyProfiles").resolvePedagogyProfile,
  isPedagogyEngineEnabled: require("./structureFunctionPedagogyEngine").isPedagogyEngineEnabled,
  generateStructureFunctionFramework: require("./structureFunctionPedagogyEngine").generateStructureFunctionFramework,
  scorePedagogicalCoverage: require("./structureFunctionPedagogyEngine").scorePedagogicalCoverage,
  formatStructureFunctionPedagogyAppendix: require("./structureFunctionPedagogyEngine").formatStructureFunctionPedagogyAppendix,
  isGcseReasoningEngineEnabled: require("./gcseReasoningEngine").isGcseReasoningEngineEnabled,
  buildReasoningChain: require("./gcseReasoningEngine").buildReasoningChain,
  scoreReasoningCoverage: require("./gcseReasoningEngine").scoreReasoningCoverage,
  buildReasoningAppendix: require("./gcseReasoningEngine").buildReasoningAppendix,
  GCSE_REASONING_STEPS: require("./gcseReasoningEngine").GCSE_REASONING_STEPS,
  resolveAuthorizedInteractions: require("./interactionAuthorityLayer").resolveAuthorizedInteractions,
  validateInteractionAuthority: require("./interactionAuthorityLayer").validateInteractionAuthority,
  auditInteractionAuthorityFromLesson: require("./interactionAuthorityLayer").auditInteractionAuthorityFromLesson,
  formatInteractionAuthorityAppendix: require("./interactionAuthorityLayer").formatInteractionAuthorityAppendix,
  enforceInteractionAuthorityOnDraft: require("./interactionAuthorityEnforcer").enforceInteractionAuthorityOnDraft,
  isTopicKindBlockedForProfile: require("./interactionAuthorityEnforcer").isTopicKindBlockedForProfile,
  countForbiddenPrimaryActivities: require("./interactionAuthorityEnforcer").countForbiddenPrimaryActivities,
  isConceptCompressionEnabled: require("./conceptCompressionEngine").isConceptCompressionEnabled,
  resolveConceptCompressionProfile: require("./conceptCompressionProfiles").resolveConceptCompressionProfile,
  resolveCompressionProfile: require("./conceptCompressionEngine").resolveCompressionProfile,
  buildConceptCompression: require("./conceptCompressionEngine").buildConceptCompression,
  formatConceptCompressionAppendix: require("./conceptCompressionEngine").formatConceptCompressionAppendix,
  scoreConceptCompressionCoverage: require("./conceptCompressionEngine").scoreConceptCompressionCoverage,
  isTeacherFirstOpeningEnabled: require("./teacherFirstKnowledgeEngine").isTeacherFirstOpeningEnabled,
  isTeacherFirstSs1Enabled: require("./teacherFirstSs1Architecture").isTeacherFirstSs1Enabled,
  getSs1CanonicalSlots: require("./teacherFirstSs1Architecture").getSs1CanonicalSlots,
  getMandatoryArchitectureSequence: require("./teacherFirstSs1Architecture").getMandatoryArchitectureSequence,
  UNIVERSAL_TEACHER_FIRST_FRAMEWORK: require("./teacherFirstKnowledgeProfiles").UNIVERSAL_TEACHER_FIRST_FRAMEWORK,
  SUBJECT_TEACHING_PROFILES: require("./teacherFirstKnowledgeProfiles").SUBJECT_TEACHING_PROFILES,
  resolveSubjectTeachingProfile: require("./teacherFirstKnowledgeProfiles").resolveSubjectTeachingProfile,
  resolveTeacherFirstKnowledgeProfile: require("./teacherFirstKnowledgeProfiles").resolveTeacherFirstKnowledgeProfile,
  buildUniversalFrameworkPlan: require("./teacherFirstKnowledgeEngine").buildUniversalFrameworkPlan,
  buildTeacherFirstOpeningPlan: require("./teacherFirstKnowledgeEngine").buildTeacherFirstOpeningPlan,
  formatTeacherFirstOpeningAppendix: require("./teacherFirstKnowledgeEngine").formatTeacherFirstOpeningAppendix,
  scoreTeacherFirstOpeningCoverage: require("./teacherFirstKnowledgeEngine").scoreTeacherFirstOpeningCoverage,
  isDashboardTeacherFirstEnabled: require("./dashboardTeacherFirstOpening").isDashboardTeacherFirstEnabled,
  buildDashboardTeacherFirstPromptSection: require("./dashboardTeacherFirstOpening").buildDashboardTeacherFirstPromptSection,
  enforceDashboardTeacherFirstOpening: require("./dashboardTeacherFirstOpening").enforceDashboardTeacherFirstOpening,
  REQUIRED_PRACTICAL_MODE_VERSION: require("./requiredPracticalMode").REQUIRED_PRACTICAL_MODE_VERSION,
  REACTION_TIME_RULER_DROP_ORIENTATION:
    require("./requiredPracticalMode").REACTION_TIME_RULER_DROP_ORIENTATION,
  isRequiredPracticalMode: require("./requiredPracticalMode").isRequiredPracticalMode,
  isReactionTimePractical: require("./requiredPracticalMode").isReactionTimePractical,
  buildRequiredPracticalOpeningPlan: require("./requiredPracticalMode").buildRequiredPracticalOpeningPlan,
  buildRequiredPracticalSs1BlockOrderSection: require("./requiredPracticalMode").buildRequiredPracticalSs1BlockOrderSection,
  buildRequiredPracticalDashboardPromptSection: require("./requiredPracticalMode").buildRequiredPracticalDashboardPromptSection,
  formatRequiredPracticalAppendix: require("./requiredPracticalMode").formatRequiredPracticalAppendix,
  REQUIRED_PRACTICAL_MANDATORY_SPECIALIST_BLOCK_KEYS:
    require("./requiredPracticalMode").REQUIRED_PRACTICAL_MANDATORY_SPECIALIST_BLOCK_KEYS,
  buildRequiredPracticalSpecialistBlocksSection:
    require("./requiredPracticalMode").buildRequiredPracticalSpecialistBlocksSection,
  enforceMandatorySpecialistBlocks: require("./requiredPracticalMode").enforceMandatorySpecialistBlocks,
  enforceReactionTimeInteractiveDiagram:
    require("./requiredPracticalMode").enforceReactionTimeInteractiveDiagram,
  buildReactionTimeInteractiveDiagramBlock:
    require("./requiredPracticalMode").buildReactionTimeInteractiveDiagramBlock,
  isSpecialistBlockContentValid: require("./requiredPracticalMode").isSpecialistBlockContentValid,
  buildRequiredPracticalReplacementDirective: require("./requiredPracticalMode").buildRequiredPracticalReplacementDirective,
  buildRequiredPracticalDashboardLessonContract: require("./requiredPracticalMode").buildRequiredPracticalDashboardLessonContract,
  isForbiddenTeacherFirstBlock: require("./requiredPracticalMode").isForbiddenTeacherFirstBlock,
  stripForbiddenTeacherFirstBlocks: require("./requiredPracticalMode").stripForbiddenTeacherFirstBlocks,
  REQUIRED_PRACTICAL_SS1_CANONICAL_SLOTS: require("./requiredPracticalMode").REQUIRED_PRACTICAL_SS1_CANONICAL_SLOTS,
  isTeachingQualityEnabled: require("./teachingQualityRubric").isTeachingQualityEnabled,
  scoreTeachingQuality: require("./teachingQualityRubric").scoreTeachingQuality,
  buildTeachingQualityReview: require("./teachingQualityRubric").buildTeachingQualityReview,
  formatTeachingQualityAppendix: require("./teachingQualityRubric").formatTeachingQualityAppendix,
  formatTeachingQualityReviewLines: require("./teachingQualityRubric").formatTeachingQualityReviewLines,
  TEACHING_QUALITY_DIMENSIONS: require("./teachingQualityRubric").TEACHING_QUALITY_DIMENSIONS,
  TEACHER_FIRST_OPENING_ORDER_VERSION: require("./teacherFirstSs1Architecture").TEACHER_FIRST_OPENING_ORDER_VERSION,
  isTeachingQualityUpgradeEnabled: require("./reasoningChainEngine").isTeachingQualityUpgradeEnabled,
  buildTeachingQualityUpgradePromptSection: require("./teachingQualityUpgrade").buildTeachingQualityUpgradePromptSection,
  evaluateTeachingQualityUpgrade: require("./teachingQualityUpgrade").evaluateTeachingQualityUpgrade,
  scoreReasoningChainCoverage: require("./reasoningChainEngine").scoreReasoningChainCoverage,
  scoreExaminerLanguageCoverage: require("./examinerLanguageEngine").scoreExaminerLanguageCoverage,
  buildExaminerLanguageV2PromptSection:
    require("./examinerLanguageV2Engine").buildExaminerLanguageV2PromptSection,
  scoreExaminerLanguageV2Coverage:
    require("./examinerLanguageV2Engine").scoreExaminerLanguageV2Coverage,
  isExaminerLanguageV2Enabled: require("./examinerLanguageV2Engine").isExaminerLanguageV2Enabled,
  buildGrade89ChallengePromptSection:
    require("./grade89ChallengeEngine").buildGrade89ChallengePromptSection,
  scoreGrade89ChallengeCoverage: require("./grade89ChallengeEngine").scoreGrade89ChallengeCoverage,
  isGrade89ChallengeEnabled: require("./grade89ChallengeEngine").isGrade89ChallengeEnabled,
  buildCoreLearningDisciplinePromptSection:
    require("./coreLearningDisciplineEngine").buildCoreLearningDisciplinePromptSection,
  scoreCoreLearningDiscipline:
    require("./coreLearningDisciplineEngine").scoreCoreLearningDiscipline,
  isCoreLearningDisciplineEnabled:
    require("./coreLearningDisciplineEngine").isCoreLearningDisciplineEnabled,
  buildSubjectIntelligencePromptSection:
    require("./subjectIntelligenceEngine").buildSubjectIntelligencePromptSection,
  scoreSubjectIntelligenceCoverage:
    require("./subjectIntelligenceEngine").scoreSubjectIntelligenceCoverage,
  isSubjectIntelligenceEnabled: require("./subjectIntelligenceEngine").isSubjectIntelligenceEnabled,
  resolveSubjectIntelligence: require("./subjectIntelligenceEngine").resolveSubjectIntelligence,
  resolveTeachingQualityProfile: require("./teachingQualityProfiles").resolveTeachingQualityProfile,
  detectUnresolvedPlaceholders: require("./teachingQualityPlaceholderGate").detectUnresolvedPlaceholders,
  detectDualOutput: require("./teachingQualityPlaceholderGate").detectDualOutput,
  validateOpeningSlots: require("./teachingQualityPlaceholderGate").validateOpeningSlots,
  evaluateTeachingQualityGate: require("./teachingQualityPlaceholderGate").evaluateTeachingQualityGate,
  buildSs1Layer2MandatoryOpeningSection:
    require("./teacherFirstKnowledgeEngine").buildSs1Layer2MandatoryOpeningSection,
  buildSs1AntiDuplicationPromptSection:
    require("./teacherFirstSs1Architecture").buildSs1AntiDuplicationPromptSection,
  isVtiaTelemetryEnabled: require("./visualTaskInteractionAuthority").isVtiaTelemetryEnabled,
  buildVtiaTelemetry: require("./visualTaskInteractionAuthority").buildVtiaTelemetry,
  aggregateVtiaTelemetry: require("./visualTaskInteractionAuthority").aggregateVtiaTelemetry,
  computeIntentPrecisionEstimate: require("./visualTaskInteractionAuthority").computeIntentPrecisionEstimate,
  formatVtiaTelemetryLines: require("./visualTaskInteractionAuthority").formatVtiaTelemetryLines,
};
