/**
 * Teacher Brain — Phase 1 entry (analysis only).
 */

const { runTeacherBrain } = require("./TeacherBrainEngine");
const {
  injectDiagramAndActivityBriefs,
  formatDiagramBrief,
  formatDragDropBrief,
  formatTextMatchBrief,
  formatTextToImageBrief,
  formatImageDropZonesBrief,
  formatStepByStepBrief,
  resolveDragDropActivityLayout,
  BRIEF_MARKER,
} = require("./diagramBriefInjector");
const { detectDragDropActivityLayout } = require("./dragDropActivityLayout");
const { formatDragDropImageDesignRequirements } = require("./dragDropVisualContract");
const { resolveInteractiveDiagramTopicKind } = require("./interactiveDiagramTopicKind");
const {
  getInteractiveDiagramPlansForTopicKind,
  formatInteractiveDiagramTopicBrief,
} = require("./interactiveDiagramTopicSpecs");
const { resolveInteractiveSequenceTopicKind } = require("./interactiveSequenceTopicKind");
const { formatInteractiveSequenceTopicBrief } = require("./interactiveSequenceTopicSpecs");

module.exports = {
  runTeacherBrain,
  injectDiagramAndActivityBriefs,
  formatDiagramBrief,
  formatDragDropBrief,
  formatTextMatchBrief,
  formatTextToImageBrief,
  formatImageDropZonesBrief,
  formatStepByStepBrief,
  resolveDragDropActivityLayout,
  detectDragDropActivityLayout,
  BRIEF_MARKER,
  formatDragDropImageDesignRequirements,
  resolveInteractiveDiagramTopicKind,
  getInteractiveDiagramPlansForTopicKind,
  formatInteractiveDiagramTopicBrief,
  resolveInteractiveSequenceTopicKind,
  formatInteractiveSequenceTopicBrief,
  extractCoreConcepts: require("./conceptExtractor").extractCoreConcepts,
  planMisconceptions: require("./misconceptionEngine").planMisconceptions,
  planRequiredDiagrams: require("./diagramPlanner").planRequiredDiagrams,
  planActivityRecommendations: require("./activityPlanner").planActivityRecommendations,
  planExamTargets: require("./examPlanner").planExamTargets,
  planRetrieval: require("./retrievalPlanner").planRetrieval,
  buildLessonCoverageMap: require("./lessonCoverageIntelligence").buildLessonCoverageMap,
  checkCoverageBeforeGeneration: require("./lessonCoverageIntelligence").checkCoverageBeforeGeneration,
  formatCoverageMapForPrompt: require("./lessonCoverageIntelligence").formatCoverageMapForPrompt,
  COGNITIVE_SKILLS: require("./lessonCoverageIntelligence").COGNITIVE_SKILLS,
  createCoverageGateFromLesson: require("./coverageGatedGeneration").createCoverageGateFromLesson,
  createCoverageGenerationGate: require("./coverageGatedGeneration").createCoverageGenerationGate,
  planCoverageGatedQuestion: require("./coverageGatedGeneration").planCoverageGatedQuestion,
  planCoverageGatedQuestionBatch: require("./coverageGatedGeneration").planCoverageGatedQuestionBatch,
  formatCoveragePlanForPrompt: require("./coverageGatedGeneration").formatCoveragePlanForPrompt,
  attachCoverageMetadata: require("./coverageGatedGeneration").attachCoverageMetadata,
  prependCoverageDirectiveToPrompt: require("./coverageGatedGeneration").prependCoverageDirectiveToPrompt,
  buildOneShotLessonCoveragePlanAppendix: require("./oneShotLessonCoveragePlan").buildOneShotLessonCoveragePlanAppendix,
  mergeOneShotCoveragePlanIntoInstructions: require("./oneShotLessonCoveragePlan").mergeOneShotCoveragePlanIntoInstructions,
  buildLessonCoverageReview: require("./lessonCoverageReview").buildLessonCoverageReview,
  resolveSubTopicProfile: require("./subTopicProfiles").resolveSubTopicProfile,
  listProfileConcepts: require("./subTopicProfiles").listProfileConcepts,
  NERVOUS_SYSTEM_STRUCTURE_PROFILE: require("./subTopicProfiles").NERVOUS_SYSTEM_STRUCTURE_PROFILE,
  classifyConcept: require("./subTopicBoundaryGuard").classifyConcept,
  validateGenerationSlot: require("./subTopicBoundaryGuard").validateGenerationSlot,
  validateBlockScope: require("./subTopicBoundaryGuard").validateBlockScope,
  scoreScopeContamination: require("./subTopicBoundaryGuard").scoreScopeContamination,
  getSubTopicBoundaryMode: require("./subTopicBoundaryGuard").getSubTopicBoundaryMode,
  isSubTopicBoundaryEnforcementEnabled: require("./subTopicBoundaryGuard").isSubTopicBoundaryEnforcementEnabled,
  buildSubTopicBoundaryContext: require("./subTopicBoundaryPlanning").buildSubTopicBoundaryContext,
  formatSubTopicBoundaryAppendix: require("./subTopicBoundaryPlanning").formatSubTopicBoundaryAppendix,
  buildBoundaryReviewFromLesson: require("./subTopicBoundaryPlanning").buildBoundaryReviewFromLesson,
  auditLessonBoundary: require("./lessonBoundaryAudit").auditLessonBoundary,
  boundaryAuditResponseMeta: require("./lessonBoundaryAudit").boundaryAuditResponseMeta,
  planBoundaryReplacements: require("./boundaryReplacementPlanner").planBoundaryReplacements,
  formatBoundaryReplacementAppendix: require("./boundaryReplacementPlanner").formatBoundaryReplacementAppendix,
  boundaryReplacementResponseMeta: require("./boundaryReplacementPlanner").boundaryReplacementResponseMeta,
  buildBoundaryReplacementFromLesson: require("./boundaryReplacementPlanner").buildBoundaryReplacementFromLesson,
  planBoundaryInteractionReplacements: require("./boundaryInteractionReplacementPlanner").planBoundaryInteractionReplacements,
  formatBoundaryInteractionReplacementAppendix: require("./boundaryInteractionReplacementPlanner").formatBoundaryInteractionReplacementAppendix,
  mergeInteractionPlanIntoReplacementPlan: require("./boundaryInteractionReplacementPlanner").mergeInteractionPlanIntoReplacementPlan,
  enforceObjectiveBoundaries: require("./objectiveBoundaryEnforcer").enforceObjectiveBoundaries,
  enforceObjectiveBoundariesOnDraft: require("./objectiveBoundaryEnforcer").enforceObjectiveBoundariesOnDraft,
  analyzeObjectiveBoundaryFromLesson: require("./objectiveBoundaryEnforcer").analyzeObjectiveBoundaryFromLesson,
  formatObjectiveBoundaryAppendix: require("./objectiveBoundaryEnforcer").formatObjectiveBoundaryAppendix,
  resolveConceptPriorityProfile: require("./conceptPriorityProfiles").resolveConceptPriorityProfile,
  isPriorityEngineEnabled: require("./conceptPriorityEngine").isPriorityEngineEnabled,
  getPriorityTier: require("./conceptPriorityEngine").getPriorityTier,
  scoreConceptPriority: require("./conceptPriorityEngine").scoreConceptPriority,
  sortConceptsByPriority: require("./conceptPriorityEngine").sortConceptsByPriority,
  formatConceptPriorityAppendix: require("./conceptPriorityEngine").formatConceptPriorityAppendix,
  buildConceptPriorityDistribution: require("./conceptPriorityEngine").buildConceptPriorityDistribution,
  resolvePedagogyProfile: require("./biologyPedagogyProfiles").resolvePedagogyProfile,
  isPedagogyEngineEnabled: require("./structureFunctionPedagogyEngine").isPedagogyEngineEnabled,
  generateStructureFunctionFramework: require("./structureFunctionPedagogyEngine").generateStructureFunctionFramework,
  scorePedagogicalCoverage: require("./structureFunctionPedagogyEngine").scorePedagogicalCoverage,
  formatStructureFunctionPedagogyAppendix: require("./structureFunctionPedagogyEngine").formatStructureFunctionPedagogyAppendix,
  isGcseReasoningEngineEnabled: require("./gcseReasoningEngine").isGcseReasoningEngineEnabled,
  buildReasoningChain: require("./gcseReasoningEngine").buildReasoningChain,
  scoreReasoningCoverage: require("./gcseReasoningEngine").scoreReasoningCoverage,
  buildReasoningAppendix: require("./gcseReasoningEngine").buildReasoningAppendix,
  GCSE_REASONING_STEPS: require("./gcseReasoningEngine").GCSE_REASONING_STEPS,
  resolveAuthorizedInteractions: require("./interactionAuthorityLayer").resolveAuthorizedInteractions,
  validateInteractionAuthority: require("./interactionAuthorityLayer").validateInteractionAuthority,
  auditInteractionAuthorityFromLesson: require("./interactionAuthorityLayer").auditInteractionAuthorityFromLesson,
  formatInteractionAuthorityAppendix: require("./interactionAuthorityLayer").formatInteractionAuthorityAppendix,
  isConceptCompressionEnabled: require("./conceptCompressionEngine").isConceptCompressionEnabled,
  resolveConceptCompressionProfile: require("./conceptCompressionProfiles").resolveConceptCompressionProfile,
  resolveCompressionProfile: require("./conceptCompressionEngine").resolveCompressionProfile,
  buildConceptCompression: require("./conceptCompressionEngine").buildConceptCompression,
  formatConceptCompressionAppendix: require("./conceptCompressionEngine").formatConceptCompressionAppendix,
  scoreConceptCompressionCoverage: require("./conceptCompressionEngine").scoreConceptCompressionCoverage,
  isTeacherFirstOpeningEnabled: require("./teacherFirstKnowledgeEngine").isTeacherFirstOpeningEnabled,
  UNIVERSAL_TEACHER_FIRST_FRAMEWORK: require("./teacherFirstKnowledgeProfiles").UNIVERSAL_TEACHER_FIRST_FRAMEWORK,
  SUBJECT_TEACHING_PROFILES: require("./teacherFirstKnowledgeProfiles").SUBJECT_TEACHING_PROFILES,
  resolveSubjectTeachingProfile: require("./teacherFirstKnowledgeProfiles").resolveSubjectTeachingProfile,
  resolveTeacherFirstKnowledgeProfile: require("./teacherFirstKnowledgeProfiles").resolveTeacherFirstKnowledgeProfile,
  buildUniversalFrameworkPlan: require("./teacherFirstKnowledgeEngine").buildUniversalFrameworkPlan,
  buildTeacherFirstOpeningPlan: require("./teacherFirstKnowledgeEngine").buildTeacherFirstOpeningPlan,
  formatTeacherFirstOpeningAppendix: require("./teacherFirstKnowledgeEngine").formatTeacherFirstOpeningAppendix,
  scoreTeacherFirstOpeningCoverage: require("./teacherFirstKnowledgeEngine").scoreTeacherFirstOpeningCoverage,
};
