/**
 * Autopilot Safety Foundation — S1.5 preparation eligibility contract V1.
 * Read-only vocabulary only. No persistence, no API, no runtime gates.
 */

const POLICY_VERSION = "autopilot-safety-preparation-eligibility-v1";

const CLASSIFICATION_ELIGIBLE = "ELIGIBLE_FOR_FUTURE_PREPARATION";
const CLASSIFICATION_NOT_ELIGIBLE = "NOT_ELIGIBLE";

const EVIDENCE_AUTHORITY = "approvalSnapshot";

const BLOCKING_REASONS = Object.freeze({
  WRONG_LIFECYCLE_STATUS: "WRONG_LIFECYCLE_STATUS",
  HISTORICAL_NO_PROVENANCE: "HISTORICAL_NO_PROVENANCE",
  MISSING_APPROVAL_SNAPSHOT: "MISSING_APPROVAL_SNAPSHOT",
  MISSING_FROZEN_PROVENANCE: "MISSING_FROZEN_PROVENANCE",
  INCOMPLETE_PROVENANCE_SIBLINGS: "INCOMPLETE_PROVENANCE_SIBLINGS",
  PROVENANCE_INTEGRITY_FAILURE: "PROVENANCE_INTEGRITY_FAILURE",
  SNAPSHOT_PROVENANCE_MISMATCH: "SNAPSHOT_PROVENANCE_MISMATCH",
  TARGET_SNAPSHOT_INTEGRITY_FAILURE: "TARGET_SNAPSHOT_INTEGRITY_FAILURE",
  TARGET_SNAPSHOT_MISMATCH: "TARGET_SNAPSHOT_MISMATCH",
  UNSUPPORTED_ACTION_TYPE: "UNSUPPORTED_ACTION_TYPE",
  UNSUPPORTED_TARGET_TYPE: "UNSUPPORTED_TARGET_TYPE",
  NON_ZERO_TARGET_COUNT: "NON_ZERO_TARGET_COUNT",
  STUDENT_CLASS_TARGET_FORBIDDEN: "STUDENT_CLASS_TARGET_FORBIDDEN",
  NOT_AN_ACTION_ADVISORY: "NOT_AN_ACTION_ADVISORY",
  UNSUPPORTED_READINESS_CLASSIFICATION: "UNSUPPORTED_READINESS_CLASSIFICATION",
  POLICY_VERSION_MISMATCH: "POLICY_VERSION_MISMATCH",
  PERMISSION_LEVEL_MISMATCH: "PERMISSION_LEVEL_MISMATCH",
  PLATFORM_CAPABILITY_BLOCKER: "PLATFORM_CAPABILITY_BLOCKER",
  UNSUPPORTED_ADVISORY_SOURCE_REF: "UNSUPPORTED_ADVISORY_SOURCE_REF",
  EXECUTION_INVARIANT_FAILURE: "EXECUTION_INVARIANT_FAILURE",
});

/** Stable ordering for deterministic multi-reason output. */
const BLOCKING_REASON_ORDER = Object.freeze([
  BLOCKING_REASONS.EXECUTION_INVARIANT_FAILURE,
  BLOCKING_REASONS.WRONG_LIFECYCLE_STATUS,
  BLOCKING_REASONS.MISSING_APPROVAL_SNAPSHOT,
  BLOCKING_REASONS.HISTORICAL_NO_PROVENANCE,
  BLOCKING_REASONS.MISSING_FROZEN_PROVENANCE,
  BLOCKING_REASONS.INCOMPLETE_PROVENANCE_SIBLINGS,
  BLOCKING_REASONS.PROVENANCE_INTEGRITY_FAILURE,
  BLOCKING_REASONS.SNAPSHOT_PROVENANCE_MISMATCH,
  BLOCKING_REASONS.POLICY_VERSION_MISMATCH,
  BLOCKING_REASONS.UNSUPPORTED_ACTION_TYPE,
  BLOCKING_REASONS.TARGET_SNAPSHOT_INTEGRITY_FAILURE,
  BLOCKING_REASONS.TARGET_SNAPSHOT_MISMATCH,
  BLOCKING_REASONS.UNSUPPORTED_TARGET_TYPE,
  BLOCKING_REASONS.NON_ZERO_TARGET_COUNT,
  BLOCKING_REASONS.STUDENT_CLASS_TARGET_FORBIDDEN,
  BLOCKING_REASONS.UNSUPPORTED_ADVISORY_SOURCE_REF,
  BLOCKING_REASONS.NOT_AN_ACTION_ADVISORY,
  BLOCKING_REASONS.UNSUPPORTED_READINESS_CLASSIFICATION,
  BLOCKING_REASONS.PERMISSION_LEVEL_MISMATCH,
  BLOCKING_REASONS.PLATFORM_CAPABILITY_BLOCKER,
]);

/**
 * Explicit preparation-safety blockers from frozen evidence.
 * Not every blockingRequirements entry disqualifies preparation eligibility.
 */
const PREPARATION_SAFETY_BLOCKERS = Object.freeze(["NO_STUDENT_SCOPE", "STUDENT_IMPACTING"]);

const ACTIONABLE_READINESS_CLASSIFICATIONS = Object.freeze([
  "REQUIRES_L2_PREPARATION",
  "REQUIRES_HUMAN_APPROVAL",
]);

const B2_ADVISORY_SOURCE_REF_PATTERN = /^provenance:v1:.+:[a-f0-9]{64}$/;

function sortBlockingReasons(reasons) {
  const unique = [...new Set(reasons)];
  return unique.sort(
    (left, right) => BLOCKING_REASON_ORDER.indexOf(left) - BLOCKING_REASON_ORDER.indexOf(right)
  );
}

module.exports = {
  POLICY_VERSION,
  CLASSIFICATION_ELIGIBLE,
  CLASSIFICATION_NOT_ELIGIBLE,
  EVIDENCE_AUTHORITY,
  BLOCKING_REASONS,
  BLOCKING_REASON_ORDER,
  PREPARATION_SAFETY_BLOCKERS,
  ACTIONABLE_READINESS_CLASSIFICATIONS,
  B2_ADVISORY_SOURCE_REF_PATTERN,
  sortBlockingReasons,
};
