# AI Content Generator for LetsRevise.com
# Usage: .\generate-content.ps1 -Subject "Maths" -Topic "Algebra" -Level "gcse" -Type "revision_notes"

param(
    [string]$Subject,
    [string]$Topic,
    [string]$Level = "gcse",
    [string]$Type = "revision_notes",
    [string]$ExamBoard = "",
    [string]$OutputPath = ""
)

# Load configuration
$configPath = Join-Path $PSScriptRoot "..\core\ai-integration\config\ai-config.json"
$config = Get-Content $configPath | ConvertFrom-Json

# Load appropriate prompt template
$promptTemplate = switch ($Type) {
    "revision_notes" { "revision-notes.txt" }
    "worksheet" { "worksheet.txt" }
    "quiz" { "quiz.txt" }
    default { "revision-notes.txt" }
}

$promptPath = Join-Path $PSScriptRoot "..\core\ai-integration\prompts\$promptTemplate"
$template = Get-Content $promptPath -Raw

# Populate template with parameters
$prompt = $template -replace "{subject}", $Subject
$prompt = $prompt -replace "{topic}", $Topic
$prompt = $prompt -replace "{level}", $Level
$prompt = $prompt -replace "{exam_board}", $ExamBoard
$prompt = $prompt -replace "{duration}", "45"
$prompt = $prompt -replace "{difficulty}", "medium"

# Determine output path
if ([string]::IsNullOrEmpty($OutputPath)) {
    # Auto-generate output path based on structure
    $basePath = "src\content"
    if ($Level -eq "a-level") { $OutputPath = "$basePath\a-level\$Subject\topics\$Topic" }
    elseif ($Level -eq "gcse") { 
        if (-not [string]::IsNullOrEmpty($ExamBoard)) {
            $OutputPath = "$basePath\gcse\$ExamBoard\$Subject\topics\$Topic"
        } else {
            $OutputPath = "$basePath\gcse\AQA\$Subject\topics\$Topic"
        }
    }
    elseif ($Level -eq "ks3") { $OutputPath = "$basePath\ks3\year7\$Subject\topics\$Topic" }
    elseif ($Level -eq "ks2") { $OutputPath = "$basePath\ks2\year6\$Subject\topics\$Topic" }
}

# Create output directory
New-Item -ItemType Directory -Path $OutputPath -Force | Out-Null

# Generate filename based on type
$filename = switch ($Type) {
    "revision_notes" { "revision-notes.md" }
    "worksheet" { "worksheet.md" }
    "quiz" { "quiz.json" }
    default { "content.md" }
}

$outputFile = Join-Path $OutputPath $filename

# Here you would integrate with actual AI API
# For now, we'll create a template file

Write-Host "Generating $Type for $Subject - $Topic ($Level)" -ForegroundColor Cyan
Write-Host "Output: $outputFile" -ForegroundColor Green

# Create sample content (replace with actual AI API call)
$sampleContent = @"
# $Subject - $Topic
## Education Level: $Level
## Exam Board: $ExamBoard
## Generated: $(Get-Date -Format "yyyy-MM-dd HH:mm:ss")

This content would be generated by AI for $Topic in $Subject at $Level level.

Replace this with actual AI-generated content using:
1. OpenAI API
2. Anthropic Claude API
3. Or other AI service

## Next Steps:
1. Add your API keys to config\api-keys.json
2. Uncomment the API call section below
3. Implement error handling
4. Add rate limiting
"@

$sampleContent | Out-File -FilePath $outputFile -Encoding UTF8

Write-Host "Content generated successfully!" -ForegroundColor Green

# Update metadata
$metadataPath = Join-Path (Split-Path $OutputPath -Parent) "topics.json"
if (Test-Path $metadataPath) {
    $metadata = Get-Content $metadataPath | ConvertFrom-Json
    $newEntry = @{
        name = $Topic
        type = $Type
        generated_date = Get-Date -Format "yyyy-MM-dd"
        file = $filename
    }
    
    $metadata.ai_generated += $newEntry
    
    # Add to topics list if not already present
    if ($metadata.topics -notcontains $Topic) {
        $metadata.topics += $Topic
    }
    
    $metadata | ConvertTo-Json -Depth 3 | Out-File -FilePath $metadataPath -Encoding UTF8
}
