export type McqGradeStatus = "correct" | "incorrect";

export type McqGradeResult = {
  status: McqGradeStatus;
  marksAwarded: number;
  totalMarks: number;
  correctIndex: number;
  correctLabel: string;
  correctOption: string;
  selectedIndex: number;
  selectedLabel: string;
  selectedOption: string;
};

export type McqOptionExplanation = {
  label: string;
  option: string;
  explanation: string;
};

export type McqFeedback = {
  whyCorrect?: string;
  whySelectedWrong?: string;
  wrongOptionExplanations: McqOptionExplanation[];
  improvementTip?: string;
  /** Short memorable exam rule (max 2 lines), shown above Revise this concept. */
  memoryRule?: string;
};

const CORRECT_ANSWER_LINE_RE = /^correct\s+answer:\s*([A-Za-z])\s*[—\-–:]\s*(.*)$/i;
const WHY_WRONG_LINE_RE = /^why\s+([A-Za-z])\s+is\s+wrong:\s*(.+)$/i;
const MEMORY_RULE_LINE_RE = /^memory\s+rule:\s*(.+)$/i;

/** Generic exam-writing advice — not useful as "Revise this concept" teaching. */
const GENERIC_REVISE_ADVICE_RE = [
  /strong gcse answers/i,
  /link cause to effect/i,
  /topic-specific terminolog/i,
  /use precise scientific vocabulary/i,
  /correct spelling/i,
  /command word/i,
  /worth \d+ mark/i,
  /more than one distinct point/i,
  /exam tip/i,
  /write in clear, complete sentences/i,
  /avoid vague phrases/i,
  /name the process and link/i,
];

function isGenericReviseAdvice(text: string): boolean {
  const t = String(text ?? "").trim();
  if (!t) return true;
  return GENERIC_REVISE_ADVICE_RE.some((re) => re.test(t));
}

function isAutoGeneratedWrongFallback(text: string): boolean {
  const t = String(text ?? "").trim();
  if (!t) return true;
  return (
    /is not correct\. The correct choice is/i.test(t) ||
    /^The correct answer is [A-D]\s*[—–-]/i.test(t)
  );
}

function firstUsableTeachingLine(candidates: Array<string | undefined>): string | undefined {
  for (const raw of candidates) {
    const t = String(raw ?? "").trim();
    if (!t || isGenericReviseAdvice(t)) continue;
    return t;
  }
  return undefined;
}

function isNegativeOnlyMisconception(text: string): boolean {
  const t = String(text ?? "").trim();
  if (!t || t.length > 160) return false;
  const hasNegation = /\b(not|doesn't|does not|isn't|is not|cannot|can't|never|no longer|instead of)\b/i.test(t);
  const teachesMechanism =
    /\b(causes|cause|leads to|results in|therefore|triggers|maintains|thickens|repairs|releases|breaks down|shed|implantation|ovulation|fertilisation|fertilization)\b/i.test(
      t
    );
  return hasNegation && !teachesMechanism;
}

function buildMcqReviseTeaching(input: {
  grade: McqGradeResult;
  whySelectedWrong?: string;
  explanation?: string;
  whyCorrectParts: string[];
  markSchemeTeachingLines: string[];
}): string | undefined {
  const { grade, whySelectedWrong, explanation, whyCorrectParts, markSchemeTeachingLines } = input;

  const misconceptionRaw =
    whySelectedWrong && !isAutoGeneratedWrongFallback(whySelectedWrong) ? whySelectedWrong : undefined;
  const misconception = firstUsableTeachingLine([misconceptionRaw]);
  const misconceptionIsNegativeOnly =
    misconception != null && isNegativeOnlyMisconception(misconception);

  const fromExplanation = firstUsableTeachingLine([explanation]);

  const fromMarkScheme = firstUsableTeachingLine([
    ...markSchemeTeachingLines,
    ...whyCorrectParts,
  ]);

  const fromCorrectOption =
    grade.correctLabel && grade.correctOption
      ? `${grade.correctLabel} — ${grade.correctOption}`
      : undefined;

  if (misconception && !misconceptionIsNegativeOnly) {
    return misconception;
  }

  return (
    fromExplanation ||
    fromMarkScheme ||
    (misconceptionIsNegativeOnly ? misconception : undefined) ||
    firstUsableTeachingLine([fromCorrectOption]) ||
    undefined
  );
}

const MEMORY_RULE_MAX_LINES = 2;
const MEMORY_RULE_MAX_LINE_CHARS = 72;
const MEMORY_RULE_MAX_TOTAL_CHARS = 120;

function validateMemoryRule(text: string): string | undefined {
  const lines = String(text ?? "")
    .split(/\n+/)
    .map((l) => l.trim())
    .filter(Boolean)
    .slice(0, MEMORY_RULE_MAX_LINES);
  if (!lines.length) return undefined;
  if (lines.some((l) => l.length > MEMORY_RULE_MAX_LINE_CHARS)) return undefined;
  const joined = lines.join("\n");
  if (joined.length > MEMORY_RULE_MAX_TOTAL_CHARS) return undefined;
  if (isGenericReviseAdvice(joined)) return undefined;
  return joined;
}

function parseExplicitMemoryRule(markScheme: string[], memoryRule?: string): string | undefined {
  const fromField = validateMemoryRule(String(memoryRule ?? ""));
  if (fromField) return fromField;
  for (const raw of markScheme) {
    const line = String(raw ?? "").trim();
    const match = line.match(MEMORY_RULE_LINE_RE);
    if (match?.[1]) {
      const parsed = validateMemoryRule(match[1]);
      if (parsed) return parsed;
    }
  }
  return undefined;
}

function tryArrowLocationMemoryRule(corpus: string): string | undefined {
  const rules: Array<{ process: RegExp; location: RegExp; label: [string, string] }> = [
    { process: /fertilisation|fertilization/i, location: /oviduct|fallopian/i, label: ["Fertilisation", "Oviduct"] },
    { process: /implantation/i, location: /uterus|uterine/i, label: ["Implantation", "Uterus"] },
  ];
  const lines: string[] = [];
  for (const rule of rules) {
    if (rule.process.test(corpus) && rule.location.test(corpus)) {
      lines.push(`${rule.label[0]} → ${rule.label[1]}`);
    }
  }
  return validateMemoryRule(lines.join("\n"));
}

function pickShortVerb(text: string, candidates: Array<{ pattern: RegExp; verb: string }>, fallback: string): string {
  for (const c of candidates) {
    if (c.pattern.test(text)) return c.verb;
  }
  return fallback;
}

function tryHormoneCycleMemoryRule(corpus: string): string | undefined {
  const lower = corpus.toLowerCase();
  const hasOestrogen = lower.includes("oestrogen") || lower.includes("estrogen");
  const hasProgesterone = lower.includes("progesterone");
  if (!hasOestrogen || !hasProgesterone) return undefined;

  const oestrogenVerb = pickShortVerb(
    corpus,
    [
      { pattern: /oestrogen[^.\n]{0,60}\b(rebuilds?|rebuilt|repairs?|repaired|thickens?|thickened)\b/i, verb: "rebuilds" },
    ],
    "rebuilds"
  );

  const progesteroneVerb = pickShortVerb(
    corpus,
    [
      { pattern: /progesterone[^.\n]{0,60}\b(maintains?|maintained|keeps?|kept)\b/i, verb: "maintains" },
    ],
    "maintains"
  );

  return validateMemoryRule(`Oestrogen ${oestrogenVerb}.\nProgesterone ${progesteroneVerb}.`);
}

function tryEnergyProcessMemoryRule(corpus: string): string | undefined {
  if (!/photosynthesis/i.test(corpus) || !/respiration/i.test(corpus)) return undefined;
  return validateMemoryRule("Photosynthesis stores.\nRespiration releases.");
}

function tryReflexArcMemoryRule(corpus: string): string | undefined {
  if (!/receptor/i.test(corpus) || !/relay/i.test(corpus) || !/response/i.test(corpus)) return undefined;
  return validateMemoryRule("Receptor → Relay → Response");
}

function deriveMemoryRuleFromCorpus(corpus: string): string | undefined {
  const text = String(corpus ?? "").trim();
  if (!text) return undefined;
  return (
    tryHormoneCycleMemoryRule(text) ||
    tryArrowLocationMemoryRule(text) ||
    tryEnergyProcessMemoryRule(text) ||
    tryReflexArcMemoryRule(text) ||
    undefined
  );
}

function buildMcqMemoryRule(input: {
  markScheme: string[];
  memoryRule?: string;
  teachingLines: string[];
  whyCorrectParts: string[];
  explanation?: string;
  whySelectedWrong?: string;
}): string | undefined {
  const explicit = parseExplicitMemoryRule(input.markScheme, input.memoryRule);
  if (explicit) return explicit;

  const schemeCorpus = [...input.teachingLines, ...input.whyCorrectParts].join("\n");
  const fromScheme = deriveMemoryRuleFromCorpus(schemeCorpus);
  if (fromScheme) return fromScheme;

  const fromExplanation = deriveMemoryRuleFromCorpus(String(input.explanation ?? ""));
  if (fromExplanation) return fromExplanation;

  const misconceptionCorpus = [input.whySelectedWrong, schemeCorpus, input.explanation].filter(Boolean).join("\n");
  return deriveMemoryRuleFromCorpus(misconceptionCorpus);
}

export function mcqOptionLabel(index: number): string {
  if (!Number.isFinite(index) || index < 0) return "";
  return String.fromCharCode(65 + index);
}

export function letterToMcqIndex(letter: string, optionCount: number): number {
  const code = String(letter || "").trim().toUpperCase().charCodeAt(0);
  if (!code || code < 65) return -1;
  const idx = code - 65;
  return idx >= 0 && idx < optionCount ? idx : -1;
}

export function gradeMcq(
  selectedIndex: number | null | undefined,
  correctIndex: number,
  options: string[],
  marks = 1
): McqGradeResult {
  const totalMarks = Math.max(1, marks || 1);
  const ci = typeof correctIndex === "number" && Number.isFinite(correctIndex) ? correctIndex : -1;
  const si =
    typeof selectedIndex === "number" && Number.isFinite(selectedIndex) ? selectedIndex : -1;
  const correctOption = ci >= 0 && options[ci] != null ? String(options[ci]).trim() : "";
  const selectedOption = si >= 0 && options[si] != null ? String(options[si]).trim() : "";
  const isCorrect = si >= 0 && ci >= 0 && si === ci;

  return {
    status: isCorrect ? "correct" : "incorrect",
    marksAwarded: isCorrect ? totalMarks : 0,
    totalMarks,
    correctIndex: ci,
    correctLabel: ci >= 0 ? mcqOptionLabel(ci) : "",
    correctOption,
    selectedIndex: si,
    selectedLabel: si >= 0 ? mcqOptionLabel(si) : "",
    selectedOption,
  };
}

function parseMarkSchemeMcqLines(markScheme: string[]): {
  whyCorrectParts: string[];
  wrongByLabel: Map<string, string>;
  teachingLines: string[];
} {
  const whyCorrectParts: string[] = [];
  const wrongByLabel = new Map<string, string>();
  const teachingLines: string[] = [];

  for (const raw of markScheme) {
    const line = String(raw ?? "").trim();
    if (!line) continue;

    const correctMatch = line.match(CORRECT_ANSWER_LINE_RE);
    if (correctMatch) {
      const trailing = (correctMatch[2] || "").trim();
      if (trailing) whyCorrectParts.push(trailing);
      continue;
    }

    const whyWrongMatch = line.match(WHY_WRONG_LINE_RE);
    if (whyWrongMatch) {
      wrongByLabel.set(whyWrongMatch[1].toUpperCase(), whyWrongMatch[2].trim());
      continue;
    }

    if (/^why\s+.+\s+is\s+correct:/i.test(line)) {
      whyCorrectParts.push(line.replace(/^why\s+.+\s+is\s+correct:\s*/i, "").trim() || line);
      continue;
    }

    if (MEMORY_RULE_LINE_RE.test(line)) {
      continue;
    }

    teachingLines.push(line);
  }

  return { whyCorrectParts, wrongByLabel, teachingLines };
}

export function buildMcqFeedback(input: {
  grade: McqGradeResult;
  options: string[];
  markScheme?: string[];
  explanation?: string;
  correctAnswer?: string;
  optionExplanations?: (string | null | undefined)[];
  /** Optional explicit memory rule from question metadata. */
  memoryRule?: string;
}): McqFeedback {
  const {
    grade,
    options,
    markScheme = [],
    explanation,
    correctAnswer,
    optionExplanations = [],
    memoryRule: explicitMemoryRule,
  } = input;

  const lines = markScheme.map((l) => String(l ?? "").trim()).filter(Boolean);
  const { whyCorrectParts, wrongByLabel, teachingLines } = parseMarkSchemeMcqLines(lines);

  const expl = String(explanation ?? "").trim();
  if (expl) whyCorrectParts.unshift(expl);

  const ca = String(correctAnswer ?? "").trim();
  if (ca && !whyCorrectParts.length) whyCorrectParts.push(ca);

  const whyCorrect = whyCorrectParts.filter(Boolean).join("\n\n") || undefined;

  const wrongOptionExplanations: McqOptionExplanation[] = [];
  options.forEach((opt, i) => {
    if (i === grade.correctIndex) return;
    const label = mcqOptionLabel(i);
    const fromScheme = wrongByLabel.get(label);
    const fromField = String(optionExplanations[i] ?? "").trim();
    const text = fromField || fromScheme;
    if (!text) return;
    wrongOptionExplanations.push({
      label,
      option: String(opt ?? "").trim(),
      explanation: text,
    });
  });

  let whySelectedWrong: string | undefined;
  if (grade.status === "incorrect" && grade.selectedIndex >= 0) {
    const selectedExpl =
      String(optionExplanations[grade.selectedIndex] ?? "").trim() ||
      wrongByLabel.get(grade.selectedLabel);
    const fromList = wrongOptionExplanations.find((w) => w.label === grade.selectedLabel)?.explanation;
    if (selectedExpl) {
      whySelectedWrong = selectedExpl;
    } else if (fromList) {
      whySelectedWrong = fromList;
    } else if (grade.selectedOption && grade.correctLabel && grade.correctOption) {
      whySelectedWrong = `"${grade.selectedOption}" is not correct. The correct choice is ${grade.correctLabel} — ${grade.correctOption}.`;
    } else if (grade.correctLabel && grade.correctOption) {
      whySelectedWrong = `The correct answer is ${grade.correctLabel} — ${grade.correctOption}.`;
    }
  }

  let improvementTip: string | undefined;
  let memoryRule: string | undefined;
  if (grade.status === "incorrect") {
    const reviseTeaching = buildMcqReviseTeaching({
      grade,
      whySelectedWrong,
      explanation: expl,
      whyCorrectParts,
      markSchemeTeachingLines: teachingLines,
    });
    improvementTip = reviseTeaching
      ? `Revise: ${reviseTeaching}`
      : "Revise: review the key idea behind the correct answer.";

    memoryRule = buildMcqMemoryRule({
      markScheme: lines,
      memoryRule: explicitMemoryRule,
      teachingLines,
      whyCorrectParts,
      explanation: expl,
      whySelectedWrong,
    });
  }

  return {
    whyCorrect,
    whySelectedWrong,
    wrongOptionExplanations,
    improvementTip,
    memoryRule,
  };
}
